ita-social-projects/EPlast-Client

.dockerignore, Dockerfile, nginx/nginx.conf
Added ability to run app in docker
=> Added Dockerfile

src/models/City/CityUser.tsx, src/pages/City/City/City.module.css, src/pages/City/City/City.tsx, src/pages/City/City/CityAdministration.tsx, src/pages/City/City/CityFollowers.tsx, src/pages/City/City/CityMembers.tsx
1. Redirect to user pages
2. City members photos
3. Confirmation modal before deleting city
=> Id city member user pages

src/pages/Club/Club/Club.tsx, src/pages/Club/Clubs/Clubs.tsx, src/pages/Club/CreateClub/CreateClub.module.css, src/pages/Club/CreateClub/CreateClub.tsx
Fix adding and editing club pages. Added spinner. Some little fix.
=> Fix adding and editing club pages.

azure-pipelines.yml, manifests/deployment.yml, manifests/service.yml
Created azure CI/CD for kubernetes deploy
=> Azure pipelines

src/pages/Club/Club/Club.module.css, src/pages/Club/CreateClub/CreateClub.tsx
Fixed the notification about the excess of the number of characters in the description of the clubs.
Changed some ccs styles.
=> Fixed Club/CreateClub UI

azure-pipelines.yml, manifests/deployment.yml, manifests/ingress-prod.yml, manifests/service.yml
=> update azure pipeline

src/pages/Distinction/DistinctionTable/DistinctionTable.tsx, src/pages/Distinction/DistinctionTable/FormEditDistinction.tsx, src/pages/SignUp/SignUp.module.css, src/pages/SignUp/SignUp.tsx
=> Fixed editting distinctions and SignUp alignment

src/pages/userPage/ActiveMembership/ActiveMembership.tsx
Deleted parantheses. Пасхалку знайдено!
=> Fix parentheses

src/pages/UserTable/ColumnsForUserTable.tsx
Added degree filter by gender and added Tooltip for degree.
=> Added degree filter and degree Tooltip

src/api/clubsApi.tsx, src/pages/Club/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/Club/Club/Club.tsx, src/pages/Club/Club/ClubAdministration.tsx, src/pages/Club/Club/ClubMembers.tsx, src/pages/Club/ClubDetailDrawer/ClubDetailDrawer.tsx, src/pages/Club/CreateClub/ClubTableColumns.tsx, src/pages/Club/CreateClub/CreateClub.less, src/pages/Club/CreateClub/CreateClub.tsx
Removed unnecessary information, resolved conflicts in addin club admin functionality.
=> Clubs conflicts resolved

src/api/clubsApi.tsx, src/pages/AnnualReport/AnnualReportTable/AnnualReportInformation/AnnualReportInformation.tsx, src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/SavedDropdown/SavedDropdown.tsx, src/pages/AnnualReport/Interfaces/ClubAnnualReport.ts, src/pages/City/CreateCity/CreateCity.tsx, src/pages/Club/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/Club/Club/Club.tsx, src/pages/Club/Club/ClubFollowers.tsx, src/pages/Club/Clubs/Clubs.tsx, src/pages/Club/CreateClub/CreateClub.less, src/pages/userPage/EditUserPage/EditUserPage.tsx, yarn.lock
Reworked annual reports table and fixed bugs at clubs pages.
=> Annual repor table reworked

src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx
=> Region annual report

src/App.tsx, src/api/clubsApi.tsx, src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx, src/pages/AnnualReport/ClubAnnualReportCreate/ClubAnnualReportCreate.tsx, src/pages/AnnualReport/ClubAnnualReportEdit/ClubAnnualReportEdit.less, src/pages/AnnualReport/ClubAnnualReportEdit/ClubAnnualReportEdit.tsx
=> Added possibility to edit, cancel and delete clubAnnualReport

src/pages/City/City/City.less, src/pages/City/City/City.tsx, src/pages/Regions/Region.less, src/pages/Regions/Region.tsx, src/pages/userPage/personalData/PersonalData.less, src/pages/userPage/personalData/UserFields.tsx
=> Responsive for user page and margin for members in regions and cities

src/components/Notifications/Messages.tsx, src/pages/Actions/ActionEvent/EventUser/EventUser.module.css, src/pages/Actions/ActionEvent/EventUser/EventUser.tsx, src/pages/SignUp/SignUp.tsx
=> Fix messages

src/pages/Actions/ActionEvent/EventUser/EventUser.tsx, src/pages/Club/CreateClub/CreateClub.tsx, src/pages/Regions/AddRegion.tsx
=> Added check for already created regions and clubs

src/pages/Actions/ActionEvent/SortedEvents.tsx, src/pages/Actions/EventsModals.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx
=> Fixed event notifications

src/components/PrivateLayout/PrivateLayout.tsx
=> Added registerUser status

src/api/blankApi.tsx, src/components/PrivateLayout/PrivateLayout.tsx, src/pages/userPage/Blanks/Blanks.tsx, src/pages/userPage/Blanks/UserAchievements/AddAchievementsModal.tsx, src/pages/userPage/Blanks/UserAchievements/ListOfAchievementsModal.tsx, src/pages/userPage/Blanks/UserBiography/AddBiographyModal.tsx, src/pages/userPage/Blanks/UserExtractFromUPU/AddExtractFromUPUModal.tsx
=> Improve blanks' formats

src/models/UserTable/User.tsx, src/pages/Actions/ActionEvent/EventUser/EventUser.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/Approvers/Approvers.tsx, src/pages/userPage/Blanks/Blanks.tsx, src/pages/userPage/EditUserPage/EditUserPage.tsx, src/pages/userPage/EditUserPage/Interface.tsx, src/pages/userPage/Interface/Interface.tsx, src/pages/userPage/Secretaries/SecretariesPage.tsx, src/pages/userPage/personalData/AvatarAndProgress.tsx, src/pages/userPage/personalData/UserFields.tsx
=> Add pseudo mail city club to User Profile

src/pages/Actions/ActionEvent/EventUser/EventUser.module.css, src/pages/userPage/Blanks/Blanks.module.css
=> Fixing bug with height of AvatarAndProgress

src/components/PrivateLayout/PrivateLayout.tsx
=> Removed duplicates

src/components/PrivateLayout/PrivateLayout.tsx
=> Hotfix of private layout

src/pages/Club/Club/Club.tsx, src/pages/Regions/Region.tsx, src/pages/userPage/Approvers/Approvers.less
=> FixRegionHistoryAndBackButton

src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx, src/pages/City/City/City.tsx, src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx, src/pages/Club/Club/Club.tsx, src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx, src/pages/userPage/ActiveMembership/PlastDegree/ModalAddPlastDegree.tsx
=> Add secretary for cities and clubs

src/pages/userPage/EditUserPage/EditUserPage.tsx, src/pages/userPage/EditUserPage/Interface.tsx, src/pages/userPage/Interface/Interface.tsx, src/pages/userPage/personalData/UserFields.tsx
=> Add UPU Degrees and Fix bug with birthday

src/App.tsx, src/api/precautionApi.tsx, src/components/PrivateLayout/PrivateLayout.tsx, src/pages/Precaution/Interfaces/Precaution.tsx, src/pages/Precaution/Interfaces/UserPrecaution.tsx, src/pages/Precaution/PrecautionTable/AddPrecautionModal.tsx, src/pages/Precaution/PrecautionTable/DeleteConfirm.tsx, src/pages/Precaution/PrecautionTable/DeleteTypeConfirm.tsx, src/pages/Precaution/PrecautionTable/DropDownPrecautionTable.tsx, src/pages/Precaution/PrecautionTable/EditPrecautionModal.tsx, src/pages/Precaution/PrecautionTable/EditPrecautionTypesModal.tsx, src/pages/Precaution/PrecautionTable/Form.module.css, src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx, src/pages/Precaution/PrecautionTable/FormEdit.module.css, src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx, src/pages/Precaution/PrecautionTable/FormEditPrecautionTypes.tsx, src/pages/Precaution/PrecautionTable/PrecautionTable.tsx, src/pages/Precaution/PrecautionTable/Table.module.css, src/pages/Precaution/PrecautionTable/columns.tsx, src/pages/userPage/personalData/AvatarAndProgress.tsx, src/pages/userPage/personalData/UserFields.tsx
=> Add precaution table

src/pages/userPage/personalData/UserFields.tsx
=> Fix bug with displayed NULL UpuDegree

src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx
=> FixAddModalButton

package-lock.json, src/pages/ResetPassword/ResetPassword.tsx, src/pages/userPage/EditUserPage/EditUserPage.tsx
=> Add better user links realisation

src/pages/Precaution/Interfaces/UserPrecaution.tsx, src/pages/Precaution/PrecautionTable/DropDownPrecautionTable.tsx, src/pages/Precaution/PrecautionTable/EditPrecautionModal.tsx, src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx, src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx, src/pages/Precaution/PrecautionTable/PrecautionTable.tsx, src/pages/Precaution/PrecautionTable/columns.tsx, src/pages/userPage/personalData/AvatarAndProgress.tsx
=> AddingPrecautionEndDate

src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx
=> FixBugWithPrecautionTable

src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx, src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx, src/pages/Precaution/PrecautionTable/columns.tsx, src/pages/userPage/personalData/AvatarAndProgress.tsx
=> AddingNewFiltersForPrecautions

src/pages/userPage/Approvers/Approvers.less, src/pages/userPage/Blanks/Blanks.module.css, src/pages/userPage/Blanks/Blanks.tsx, src/pages/userPage/personalData/AvatarAndProgress.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx
=> Fix conflict in AvatarAndProgress. height in Aprovers and make Blanks non-sticky

src/api/authorizeApi.ts
=> Fixed controller calling

src/api/UserApi.tsx, src/pages/userPage/Interface/Interface.tsx, src/pages/userPage/personalData/PersonalData.less, src/pages/userPage/personalData/UserFields.tsx
=> Add Short Profile

src/api/authorizeApi.ts, src/pages/UserTable/DropDownUserTable.tsx, src/pages/UserTable/UserTable.tsx
=> Added ResendEmailRegistr

src/api/precautionApi.tsx, src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx
=> AddNewApiAndFilter

src/App.tsx, src/api/governingBodiesApi.tsx, src/api/precautionApi.tsx, src/api/regionsApi.tsx, src/components/PrivateLayout/PrivateLayout.tsx, src/models/RegionBoard/RegionBoardForAdmin.tsx, src/models/RegionBoard/RegionBoardProfile.tsx, src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx, src/pages/Documents/FormAddDocument.tsx, src/pages/RegionsBoard/AddDocModal.tsx, src/pages/RegionsBoard/RegionBoard.tsx, src/pages/RegionsBoard/RegionBoardAdministration.tsx, src/pages/RegionsBoard/RegionBoardDocuments.tsx, src/pages/RegionsBoard/RegionBoardEdit.tsx, src/pages/RegionsBoard/RegionBoardMembers.tsx, src/pages/RegionsBoard/RegionsBoardDetailDrawer.tsx
=> Add regions board

src/pages/Precaution/PrecautionTable/PrecautionTable.tsx, src/pages/RegionsBoard/RegionBoard.tsx, src/pages/RegionsBoard/RegionBoardEdit.tsx, src/pages/RegionsBoard/RegionsBoardDetailDrawer.tsx
=> RedactRegionBoardPage

src/pages/userPage/Approvers/Approvers.tsx
=> Added notification on Поручення creation

src/pages/DecisionTable/FormAddDecision.tsx
=> File attachment bug fix after decision submission

src/pages/userPage/EditUserPage/EditUserPage.tsx
=> Edit profile bug fix

src/pages/Contacts/Contacts.tsx, src/pages/userPage/EditUserPage/EditUserPage.tsx
=> Contacts deleted phone number fix

src/pages/userPage/EditUserPage/EditUserPage.tsx
=> added trims and fixed date

src/pages/userPage/EditUserPage/EditUserPage.tsx
=> fixed inputs

src/pages/Actions/ActionEvent/EventUser/EventUser.tsx, src/pages/Precaution/PrecautionTable/columns.tsx, src/pages/SignUp/verification.ts
=> Some bugs fixes

src/pages/DecisionTable/DecisionTable.tsx, src/pages/DecisionTable/FormAddDecision.module.css, src/pages/userPage/EditUserPage/EditUserPage.tsx
=> Fixed some bugs

src/pages/ChangePassword/ChangePassword.tsx
=> Fixed changePassword

src/pages/Statistics/StatisticsCities.less, src/pages/Statistics/StatisticsCities.tsx, src/pages/Statistics/StatisticsRegions.less, src/pages/Statistics/StatisticsRegions.tsx
=> Statistics page

src/components/HistoryNavi/HistoryDrawer.tsx, src/components/HistoryNavi/historyPseudo.tsx, src/components/PrivateLayout/PrivateLayout.tsx, src/pages/City/City/City.tsx, src/pages/Club/Clubs/Clubs.tsx, src/pages/Contacts/Contacts.tsx, src/pages/DecisionTable/DropDownDecision.tsx, src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx, src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx, src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx, src/pages/UserTable/DropDownUserTable.tsx, src/pages/UserTable/UserTable.tsx, src/pages/userPage/Blanks/UserAchievements/ListOfAchievementsModal.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx
=> Fixed some warning, add keys

src/components/PrivateLayout/PrivateLayout.tsx, src/pages/AnnualReport/AnnualReportTable/FormAnnualReportRegion.tsx, src/pages/DecisionTable/DropDownDecision.tsx, src/pages/UserTable/AddRegionAdministratorForm.tsx, src/pages/UserTable/ChangeUserRoleForm.tsx, src/pages/UserTable/ColumnsForUserTable.tsx, src/pages/userPage/personalData/AvatarAndProgress.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx
=> Changed roles

src/pages/SignIn/SignIn.module.css
=> fixed password input background

src/pages/Club/Clubs/Clubs.tsx
=> fixed pagination sizeChanger

src/api/adminApi.tsx, src/pages/UserTable/Interfaces/TableFilterParameters.tsx, src/pages/UserTable/UserTable.tsx
=> Searchdata

src/pages/UserTable/ColumnsForUserTable.tsx, src/pages/UserTable/UserTable.tsx
=> Search user table

src/api/AnnualReportApi.tsx, src/api/clubsApi.tsx, src/api/regionsApi.tsx, src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.less, src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/CitySelectModal/CitySelectModal.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx, src/pages/AnnualReport/AnnualReportTable/ClubSelectModal/ClubSelectModal.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/UnconfirmedDropdown/UnconfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/UnconfirmedDropdown/UnconfirmedDropdownProps.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/UnconfirmedDropdown/UnconfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/UnconfirmedDropdown/UnconfirmedDropdownProps.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/ConfirmedDropdown/ConfirmedRegionDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/ConfirmedDropdown/ConfirmedRegionDropdownProps.tsx, src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportTable.tsx
=> Annual reports

src/api/AnnualReportApi.tsx, src/api/clubsApi.tsx, src/api/regionsApi.tsx, src/pages/AnnualReport/AnnualReportCreate/AnnualReportCreate.tsx, src/pages/AnnualReport/AnnualReportEdit/AnnualReportEdit.tsx, src/pages/AnnualReport/AnnualReportForm/AnnualReportForm.tsx, src/pages/AnnualReport/AnnualReportForm/AnnualReportFormProps.tsx, src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.less, src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/CitySelectModal/CitySelectModal.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx, src/pages/AnnualReport/AnnualReportTable/ClubSelectModal/ClubSelectModal.tsx, src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportTable.tsx, src/pages/AnnualReport/ClubAnnualReportCreate/ClubAnnualReportCreate.tsx, src/pages/AnnualReport/ClubAnnualReportEdit/ClubAnnualReportEdit.tsx, src/pages/AnnualReport/Interfaces/AnnualReport.ts, src/pages/AnnualReport/Interfaces/City.ts, src/pages/AnnualReport/Interfaces/ClubAnnualReport.ts
=> Annual report

src/pages/UserTable/UserTable.tsx
=> Fix search

src/App.less, src/api/adminApi.tsx, src/models/City/CityMember.tsx, src/pages/DecisionTable/FormAddDecision.tsx, src/pages/userPage/Approvers/Approvers.tsx
=> Mentions on Decisions

src/api/citiesApi.tsx, src/pages/UserTable/DropDownUserTable.tsx, src/pages/UserTable/UserTable.tsx
=> Add access for User Table

src/App.less, src/api/decisionsApi.tsx, src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx, src/pages/City/City/City.tsx, src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx, src/pages/DecisionTable/DecisionTable.tsx, src/pages/DecisionTable/DropDownDecision.tsx, src/pages/DecisionTable/FormAddDecision.tsx, src/pages/DecisionTable/FormEditDecision.tsx, src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx, src/pages/Distinction/DistinctionTable/FormEditDistinction.tsx, src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx, src/pages/KadraVykhovnykiv/AddNewKadraForm.tsx, src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx, src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx, src/pages/Regions/AddRegionSecretaryForm.tsx, src/pages/RegionsBoard/RegionBoard.tsx
=> Accesses fixes on Decisions & Precautions/Kadra updates

src/pages/City/City/City.tsx, src/pages/Club/Club/Club.tsx, src/pages/Regions/Region.tsx
=> Access levels for regions clubs cities

src/components/PrivateLayout/PrivateLayout.tsx, src/pages/Home/Home.tsx, src/pages/UserTable/DropDownUserTable.tsx, src/pages/UserTable/UserTable.module.css, src/pages/UserTable/UserTable.tsx
=> Access level

src/pages/userPage/EditUserPage/EditUserPage.tsx
=> Fix regular expressions on EditUserPage

src/pages/userPage/Blanks/Blanks.tsx, src/pages/userPage/EditUserPage/EditUserPage.tsx
=> Edit user page

src/pages/UserTable/DropDownUserTable.tsx
=> Member of organization can view profiles users in UserTable

src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx, src/pages/City/AddDocumentModal/AddDocumentModal.tsx, src/pages/Club/AddDocumentModal/AddDocumentModal.less, src/pages/Club/AddDocumentModal/AddDocumentModal.tsx, src/pages/DecisionTable/FormAddDecision.tsx, src/pages/DecisionTable/columns.tsx, src/pages/Documents/FormAddDocument.tsx, src/pages/Documents/columns.tsx, src/pages/KadraVykhovnykiv/AddNewKadraForm.tsx, src/pages/KadraVykhovnykiv/UpdateKadraForm.tsx, src/pages/Regions/AddDocModal.tsx, src/pages/Regions/AddDocumentModal.less, src/pages/userPage/Blanks/UserAchievements/AddAchievementsModal.tsx, src/pages/userPage/Blanks/UserBiography/AddBiographyModal.tsx, src/pages/userPage/Blanks/UserExtractFromUPU/AddExtractFromUPUModal.tsx
=> Various Bugs fixes

src/pages/Club/AddAdministratorModal/AddAdministratorModal.tsx
=> Fixed two notifications on hovels

src/pages/userPage/EditUserPage/EditUserPage.module.css, src/pages/userPage/personalData/PersonalData.less
=> Fixed wrong space between text fields

src/pages/userPage/personalData/AvatarAndProgress.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx
=> Changed progress bar

src/pages/userPage/ActiveMembership/ActiveMembership.tsx
=> Fixed bug with information on ActiveMembership Page

src/pages/UserTable/ChangeUserRoleForm.tsx, src/pages/UserTable/ChangeUserRoleModal.tsx, src/pages/UserTable/ColumnsForUserTable.tsx, src/pages/UserTable/DropDownUserTable.tsx
=> Fix bug with former user

src/pages/Statistics/StatisticsCities.tsx, src/pages/Statistics/StatisticsRegions.tsx
dev
ToDo
Fixed the view of percents on a chart in statistics page
ToDo
=> Fixing_bug_with_wrong_percentage

src/pages/ResetPassword/ResetPassword.tsx
=> Added validator to password

src/pages/ResetPassword/ResetPassword.tsx
=> Changed autocomplete on ResetPasswordPage

src/pages/UserTable/ColumnsForUserTable.tsx, src/pages/userPage/Approvers/Approvers.tsx, src/pages/userPage/Blanks/Blanks.tsx, src/pages/userPage/personalData/AvatarAndProgress.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx
=> Fixed bugs

src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx, src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.tsx
=> Fix_bug_with_wrong_event_quantity

src/pages/DecisionTable/DecisionTable.tsx, src/pages/DecisionTable/DropDownDecision.tsx, src/pages/Distinction/DistinctionTable/FormEditDistinction.tsx, src/pages/Documents/DocumentsTable.tsx, src/pages/Documents/DropDownDocuments.tsx, src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx, src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx
=> Precautions update & Pdf convertation for Methodic Documents

src/components/Notifications/Messages.tsx, src/pages/AnnualReport/AnnualReportCreate/AnnualReportCreate.tsx, src/pages/AnnualReport/AnnualReportEdit/AnnualReportEdit.tsx, src/pages/AnnualReport/AnnualReportMenu.less, src/pages/AnnualReport/AnnualReportMenu.tsx, src/pages/AnnualReport/AnnualReportStatus.tsx, src/pages/AnnualReport/AnnualReportTable/AnnualReportInformation/AnnualReportInformation.less, src/pages/AnnualReport/AnnualReportTable/AnnualReportInformation/AnnualReportInformation.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReportInformation/ClubAnnualReportInformation.tsx, src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportInformation.tsx, src/pages/AnnualReport/ClubAnnualReportCreate/ClubAnnualReportCreate.tsx, src/pages/AnnualReport/ClubAnnualReportEdit/ClubAnnualReportEdit.tsx, src/pages/AnnualReport/RegionAnnualReportCreateEditView/RegionAnnualReportCreate.tsx, src/pages/AnnualReport/RegionAnnualReportCreateEditView/RegionAnnualReportEdit.tsx
=> Region report

src/api/UserApi.tsx, src/pages/UserTable/DropDownUserTable.tsx, src/pages/UserTable/UserTable.tsx, src/pages/userPage/Approvers/Approvers.tsx
=> Fixed bug with deleting city approve

src/models/Club/ClubUser.tsx, src/pages/City/City/City.tsx, src/pages/City/City/CityMembers.tsx, src/pages/Club/Club/Club.tsx, src/pages/Club/Club/ClubMembers.tsx
dev
display users in when added by the administrator add admin and create club
ToDo
ToDo
=> Add creat clubs and  display users in when added by the administrator

src/pages/ChangePassword/ChangePassword.module.css, src/pages/ChangePassword/ChangePassword.tsx
=> Change password

src/api/api.ts, src/components/PrivateLayout/PrivateLayout.tsx, src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx, src/pages/Actions/ActionEvent/EventUser/EventUser.tsx, src/pages/AnnualReport/AnnualReportTable/AnnualReportInformation/AnnualReportInformation.tsx, src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReportInformation/ClubAnnualReportInformation.tsx, src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportInformation.tsx, src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportTable.tsx, src/pages/AnnualReport/ClubAnnualReportEdit/ClubAnnualReportEdit.tsx, src/pages/Club/Club/ClubMembers.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/Approvers/Approvers.tsx, src/pages/userPage/Blanks/Blanks.tsx, src/pages/userPage/Interface/Interface.tsx, src/pages/userPage/Secretaries/SecretariesPage.tsx, src/pages/userPage/personalData/AvatarAndProgress.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx, src/pages/userPage/personalData/PersonalData.less, src/pages/userPage/personalData/UserFields.tsx
=> Fixxed approvers page

src/components/Notifications/Messages.tsx, src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx
=> Fixed Incorrect error message appears  #1051

src/pages/City/City/City.less, src/pages/City/City/City.tsx, src/pages/Club/Club/Club.less, src/pages/Club/Club/Club.tsx, src/pages/GoverningBody/GoverningBody/GoverningBody.less, src/pages/GoverningBody/GoverningBody/GoverningBody.tsx, src/pages/Regions/Region.less, src/pages/Regions/Region.tsx, src/pages/RegionsBoard/RegionBoard.tsx
=> Removed (hidden) link on Documents section #1329

src/pages/UserTable/DropDownUserTable.tsx
=> Fixed access levels on UserTable

src/api/UserApi.tsx
=> fixed bug on approvePage

src/components/NotificationBox/NotificationBox.less, src/components/NotificationBox/NotificationBox.tsx
=> Made NotificationBox responsible for phones.

src/pages/Regions/Region.tsx, src/pages/Regions/RegionDocuments.tsx
=> Fixed some bugs for access levels on the region documents

src/pages/Actions/ActionEvent/EventInfo/EventDetails.less, src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.tsx, src/pages/Actions/Actions.module.css
=> Fixed on Event page text fonts and styles  #1353

src/pages/City/City/City.tsx, src/pages/Club/Club/Club.tsx
=> Fixed a mismatch in JoinCity and JoinHovel #1356

src/api/AnnualReportApi.tsx, src/api/api.ts, src/api/clubsApi.tsx, src/pages/AnnualReport/AnnualReportMenu.tsx, src/pages/AnnualReport/AnnualReportTable/AnnualReportInformation/AnnualReportInformation.tsx, src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/CitySelectModal/CitySelectModal.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReportInformation/ClubAnnualReportInformation.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/ConfirmedDropdown/ConfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/ConfirmedDropdown/ConfirmedDropdownProps.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/SavedDropdown/SavedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/SavedDropdown/SavedDropdownProps.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/UnconfirmedDropdown/UnconfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/UnconfirmedDropdown/UnconfirmedDropdownProps.tsx, src/pages/AnnualReport/ClubAnnualReportCreate/ClubAnnualReportCreate.tsx, src/pages/AnnualReport/ClubAnnualReportEdit/ClubAnnualReportEdit.tsx, src/pages/Club/Club/Club.tsx
=> pdfconvertation on CityAnnualReport

src/components/Notifications/Messages.tsx, src/config.ts, src/pages/City/City/City.tsx, src/pages/Club/AddDocumentModal/AddDocumentModal.tsx, src/pages/Regions/AddDocModal.tsx, src/pages/Regions/Region.tsx, src/pages/userPage/Blanks/Blanks.module.css
=> Improved document sections

src/pages/Statistics/StatisticsCities.tsx
=> Fixed country field in Statistics Cities.

src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx, src/pages/DecisionTable/FormAddDecision.module.css, src/pages/DecisionTable/FormAddDecision.tsx, src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx, src/pages/Documents/FormAddDocument.tsx, src/pages/KadraVykhovnykiv/AddNewKadraForm.tsx, src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx
=> Fixed dynamic dropdowns and datepickers

src/components/Notifications/Messages.tsx, src/pages/City/AddDocumentModal/AddDocumentModal.tsx, src/pages/Club/AddDocumentModal/AddDocumentModal.tsx, src/pages/Regions/AddDocModal.tsx
=> Prevent uploading emptyFiles in Region,City,Club

src/api/UserApi.tsx, src/components/PrivateLayout/PrivateLayout.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.module.css, src/pages/userPage/EditUserPage/EditUserPage.less, src/pages/userPage/EditUserPage/EditUserPage.module.css, src/pages/userPage/EditUserPage/EditUserPage.tsx, src/pages/userPage/Menu/Menu.tsx, src/pages/userPage/personalData/AvatarAndProgress.tsx, src/pages/userPage/personalData/PersonalData.less, src/pages/userPage/personalData/PersonalData.tsx, src/pages/userPage/personalData/UserFields.tsx
=> Changed EditProfile page

src/pages/userPage/Secretaries/Secretaries.less, src/pages/userPage/Secretaries/SecretariesPage.tsx
=> Fixed bug with style on SecretariesPage

src/pages/userPage/Blanks/Blanks.tsx
=> Fixed bug with document tooltip

src/pages/Documents/columns.tsx
=> Fixed 'the date was not displayed in the ‘Date’ column(invalid date)' #1396

src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx, src/pages/City/City/City.tsx, src/pages/City/City/CityAdministration.tsx
=> Fix display and update administrators when manipulating them in cities

src/pages/Statistics/StatisticsCities.tsx
=> Fixed bug with statistics on cities

src/api/blankApi.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCreate.module.css, src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx, src/pages/City/AddDocumentModal/AddDocumentModal.tsx, src/pages/City/CreateCity/CreateCity.tsx, src/pages/Club/AddDocumentModal/AddDocumentModal.tsx, src/pages/Club/CreateClub/CreateClub.tsx, src/pages/DecisionTable/FormAddDecision.tsx, src/pages/Documents/FormAddDocument.tsx, src/pages/GoverningBody/AddDocumentModal/AddDocumentModal.tsx, src/pages/GoverningBody/CreateGoverningBody.tsx, src/pages/Regions/AddDocModal.tsx, src/pages/Regions/AddRegion.tsx, src/pages/Regions/RegionEdit.tsx, src/pages/RegionsBoard/AddDocModal.tsx, src/pages/RegionsBoard/RegionBoardEdit.tsx, src/pages/userPage/Blanks/UserAchievements/AddAchievementsModal.tsx, src/pages/userPage/Blanks/UserBiography/AddBiographyModal.tsx, src/pages/userPage/Blanks/UserExtractFromUPU/AddExtractFromUPUModal.tsx, src/pages/userPage/EditUserPage/EditUserPage.tsx
=> Image extenshion

src/pages/DecisionTable/FormAddDecision.tsx
addition to previos commit.
dev
ToDo
ToDo
ToDo
=> Fixed [Decision] button 'Видалити файл' isn't aligned #1406

src/pages/userPage/Approvers/Approvers.less, src/pages/userPage/Approvers/Approvers.tsx
=> Fixed styles on ApproversPage

src/pages/ResetPassword/ResetPassword.tsx
=> Fixed bug with spelling mistakes on password

src/api/blankApi.tsx, src/models/Blank/BlankDocument.tsx, src/pages/userPage/Blanks/Blanks.tsx, src/pages/userPage/Blanks/UserAchievements/AddAchievementsModal.tsx, src/pages/userPage/Blanks/UserBiography/AddBiographyModal.tsx, src/pages/userPage/Blanks/UserExtractFromUPU/AddExtractFromUPUModal.tsx
=> Fixed bug with blanks

src/pages/Actions/ActionEvent/ActionEvent.module.css, src/pages/Actions/ActionEvent/ActionEvent.tsx
=> Fixed Space between Menu and P #1414

src/components/PrivateLayout/PrivateLayout.tsx, src/pages/UserTable/ColumnsForUserTable.tsx
=> Update user table

src/pages/City/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx, src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx, src/pages/Regions/AddRegionSecretaryForm.tsx
=> Fixed bug with add administrator modal

src/pages/userPage/Menu/Menu.tsx
=> Fixed bug with menu

src/pages/userPage/personalData/PersonalData.less, src/pages/userPage/personalData/UserFields.tsx
=> Fixed bug with short personal profile

src/components/Header/Header.module.css, src/components/Header/HeaderContainer.tsx
=> Aligned profile icon

src/pages/Actions/ActionEvent/EventUser/EventUser.module.css, src/pages/userPage/ActiveMembership/ActiveMembership.module.css, src/pages/userPage/Blanks/Blanks.module.css, src/pages/userPage/Blanks/Blanks.tsx, src/pages/userPage/personalData/PersonalData.less
=> Fixed styles

src/pages/DecisionTable/columns.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
also fixed bug #1424 
dev
ToDo
ToDo
ToDo
=> Changes with buttons on add/change degree

src/pages/City/City/City.tsx, src/pages/Regions/AddRegionSecretaryForm.tsx
also fix bug  #1223
dev
ToDo
ToDo
ToDo
=> Change access levels for button More in city  documents #1429

src/components/PrivateLayout/PrivateLayout.tsx, src/pages/UserTable/ChangeUserCityForm.tsx, src/pages/UserTable/ChangeUserClubForm.tsx, src/pages/UserTable/ChangeUserRegionForm.tsx, src/pages/UserTable/ColumnsForUserTable.tsx
=> fixed size of stage on usertable, added autocomplite

src/api/documentsApi.ts, src/pages/Actions/ActionEvent/EventCard/EventCard.tsx, src/pages/Actions/ActionEvent/EventUser/EventUser.tsx, src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.less, src/pages/Club/Club/Club.tsx, src/pages/KadraVykhovnykiv/columns.tsx, src/pages/Regions/RegionAdministration.tsx, src/pages/RegionsBoard/AddDocModal.tsx, src/pages/RegionsBoard/RegionBoard.tsx, src/pages/UserTable/ColumnsForUserTable.tsx, src/pages/UserTable/Interfaces/TableFilterParameters.tsx, src/pages/UserTable/UserTable.tsx, src/pages/userPage/personalData/AvatarAndProgress.tsx
=> User table

src/pages/City/City/City.tsx, src/pages/City/City/CityAdministration.tsx, src/pages/City/City/CityDocuments.tsx, src/pages/Club/Club/Club.tsx, src/pages/Regions/Region.tsx
=> Updated access levels Regions, Clubs, Cities

src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.module.css, src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.tsx, src/pages/Actions/ActionEvent/EventUser/EventUser.module.css, src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.module.css, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
=> Fixed overlapped button with the search box in minimized browser window #1441 and change degree container

src/pages/GoverningBody/AddDocumentModal/AddDocumentModal.less, src/pages/RegionsBoard/AddDocModal.tsx
=> Add file name input for regions board documentation

src/models/GllobalValidations/DescriptionValidation.tsx
=> Fix bug with empty post index in okruga creation form

src/pages/GoverningBody/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx, src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
=> Add user access for creating governing body sectors

src/pages/RegionsBoard/RegionBoardDocuments.tsx
=> Add delete document modal on documents page for regions board

src/pages/City/City/City.tsx, src/pages/Regions/CitiesRedirectForm.tsx, src/pages/Regions/Region.tsx
=> Updated city documents and deleting region

src/pages/RegionsBoard/AddDocModal.tsx
=> Restrict file name length

src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.module.css, src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.module.css
Fields in Add degree modal and change user dates were out of boundaries of form
=> Made forms in active membership responsive to mobile devices.

src/pages/City/City/City.tsx, src/pages/Club/Club/Club.tsx, src/pages/Regions/Region.tsx, src/pages/Regions/RegionMembers.tsx
=> Region documents

src/pages/UserTable/ChangeUserCityForm.tsx, src/pages/UserTable/ChangeUserClubForm.tsx, src/pages/UserTable/ChangeUserRegionForm.tsx, src/pages/UserTable/DropDownUserTable.tsx, src/pages/UserTable/UserTable.tsx
=> Update user table. Fixed access levels for admins 

src/pages/GoverningBody/GoverningBody/GoverningBody.tsx, src/pages/GoverningBody/Sector/Sector.tsx, src/pages/RegionsBoard/RegionBoard.tsx
=> Add counters for documents

src/pages/Precaution/PrecautionTable/columns.tsx
=> Fixed filter on precaution

src/pages/City/City/City.tsx, src/pages/Club/Club/Club.tsx
=> Small update

src/api/governingBodiesApi.tsx, src/pages/userPage/Approvers/Approvers.tsx, src/pages/userPage/Interface/Interface.tsx, src/pages/userPage/Secretaries/SecretariesPage.tsx, src/pages/userPage/Secretaries/SecretaryModel.tsx, src/pages/userPage/Secretaries/UserCitySecretaryTable.tsx, src/pages/userPage/Secretaries/UserClubSecretaryTable.tsx, src/pages/userPage/Secretaries/UserGoverningBodySecretaryTable.tsx, src/pages/userPage/Secretaries/UserRegionSecretaryTable.tsx, src/pages/userPage/Secretaries/columnsClubs.tsx, src/pages/userPage/Secretaries/columnsGoverningBodies.tsx, src/pages/userPage/personalData/AvatarAndProgress.tsx, src/pages/userPage/personalData/UserFields.tsx
=> Display the role of the governing body in secretaries ( "Діловодства" )tab  

src/pages/GoverningBody/AddAdministratorModal/AddAdministrationModal.less, src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx
=> Fix unaligned error message

src/pages/Contacts/Contacts.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/Secretaries/UserCitySecretaryTable.tsx, src/pages/userPage/Secretaries/UserClubSecretaryTable.tsx, src/pages/userPage/Secretaries/UserGoverningBodySecretaryTable.tsx, src/pages/userPage/Secretaries/UserRegionSecretaryTable.tsx
=> Reduce pageSize in tables Secretaries, change icon on Contacts page

src/models/GoverningBody/GoverningBodyAdmin.tsx, src/models/GoverningBody/GoverningBodyUser.tsx, src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx, src/pages/GoverningBody/GoverningBody/GoverningBodyAdministration.tsx, src/pages/RegionsBoard/RegionBoard.tsx, src/pages/RegionsBoard/RegionBoardAdministration.tsx
=> Fix bug add admin email on governing body admins page

src/pages/GoverningBody/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/GoverningBody/GoverningBody/GoverningBodyAdministration.tsx
=> Add email field to edit modal

src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx, src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx, src/pages/Precaution/PrecautionTable/PrecautionTable.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx
=> Fix  few bugs on precautions, distinctions, acces levels on activeMembership

src/pages/userPage/EditUserPage/EditUserPage.tsx
=> Fixed [Wrong redirection] after Personal profile data editing #1467

src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
=> Fix decisions button on governing body

src/pages/SignUp/SignUp.tsx
=> Fixed redirect, on sign in page after successfull registration

src/pages/City/City/CityDocuments.tsx, src/pages/Club/Club/Club.tsx, src/pages/Club/Club/ClubDocuments.tsx
=> Fixed a few bugs with access levels

src/components/NotificationBox/NotificationBox.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx, src/pages/userPage/Approvers/Approvers.tsx, src/pages/userPage/EditUserPage/EditUserPage.less, src/pages/userPage/EditUserPage/EditUserPage.module.css, src/pages/userPage/EditUserPage/EditUserPage.tsx
=> Responsive design, fixed access levels on degrees

src/App.tsx, src/api/governingBodySectorsApi.tsx, src/models/GoverningBody/Sector/SectorAdmin.tsx, src/models/GoverningBody/Sector/SectorUser.tsx, src/models/Roles/Roles.tsx, src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx, src/pages/GoverningBody/AddAdministratorModal/EditAdministratorModal.tsx, src/pages/GoverningBody/GoverningBody/GoverningBody.tsx, src/pages/GoverningBody/GoverningBody/GoverningBodyAdministration.tsx, src/pages/GoverningBody/Sector/AddSectorAdminForm.tsx, src/pages/GoverningBody/Sector/EditAdminModal.tsx, src/pages/GoverningBody/Sector/Sector.tsx, src/pages/GoverningBody/Sector/SectorAdministration.tsx
=> Sector administration

src/pages/GoverningBody/GoverningBody/GoverningBody.tsx, src/pages/GoverningBody/Sector/Sector.tsx, src/pages/RegionsBoard/RegionBoard.tsx
=> Fix documents count

src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReportInformation/ClubAnnualReportInformation.tsx, src/pages/AnnualReport/ClubAnnualReportCreate/ClubAnnualReportCreate.tsx, src/pages/AnnualReport/ClubAnnualReportEdit/ClubAnnualReportEdit.tsx, src/pages/AnnualReport/ClubAnnualReportForm/ClubAnnualReportForm.tsx, src/pages/AnnualReport/ClubAnnualReportForm/ClubAnnualReportTableColumns.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx
=> new club anual report and fix some bugs 

src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx, src/pages/KadraVykhovnykiv/AddNewKadraForm.tsx, src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx
=> Add wrong register number check

src/pages/GoverningBody/AddAdministratorModal/EditAdministratorModal.tsx, src/pages/GoverningBody/Sector/EditAdminModal.tsx, src/pages/GoverningBody/Sector/EditSector.tsx
=> Fix sectors edit page

src/models/Region/RegionDocument.tsx, src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx, src/pages/City/City/City.tsx, src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx, src/pages/Club/Club/Club.tsx, src/pages/Regions/AddRegionSecretaryForm.tsx, src/pages/Regions/Region.tsx, src/pages/Regions/RegionMembers.tsx
=> Fixed user being head and headDeputy at the same

src/pages/GoverningBody/GoverningBody/GoverningBody.less, src/pages/GoverningBody/GoverningBody/GoverningBodyAdministration.tsx, src/pages/GoverningBody/Sector/SectorAdministration.tsx
=> Add email tooltips for administration

src/api/regionsBoardApi.tsx, src/pages/RegionsBoard/RegionBoard.tsx, src/pages/RegionsBoard/RegionBoardDocuments.tsx
=> Fix access for registered user

src/pages/Regions/Region.tsx
=> Added notification about successful region delete

src/components/PrivateLayout/PrivateLayout.tsx, src/pages/DecisionTable/DecisionTable.tsx, src/pages/DecisionTable/Table.module.css, src/pages/userPage/EditUserPage/EditUserPage.tsx, src/pages/userPage/Secretaries/Secretaries.less, src/pages/userPage/personalData/UserFields.tsx
=> Fixed bugs (#1530, #1520, and one more about set first letter in city uppercased)

src/components/PrivateLayout/PrivateLayout.tsx, src/pages/Distinction/DistinctionTable/FormEditDistinctionTypes.tsx, src/pages/Distinction/DistinctionTable/columns.tsx, src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx, src/pages/userPage/personalData/PersonalData.less, src/pages/userPage/personalData/UserFields.tsx
=>  Fixed bug (the long title of the award goes to another page. #1533)

src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/City/AddDocumentModal/AddDocumentModal.tsx, src/pages/City/City/CityMembers.tsx, src/pages/Club/AddDocumentModal/AddDocumentModal.tsx, src/pages/Club/Club/ClubAdministration.tsx, src/pages/Club/Club/ClubMembers.tsx, src/pages/Club/Clubs/SortedClubs.tsx, src/pages/Club/CreateClub/CreateClub.tsx
bugs:
[Hovels/Курені] The hovel's name does not fit in text box #1550
[Hovels/Курені] The full names of the hovels aren't visible on the hovel's page #1548
[Hovel] [City] The system does not display confirmation window when we delete user from members #1522
[Documents type on City and Hovel] section is shifted #1545
dev
ToDo
ToDo
ToDo
=> Fixed a few bugs on Hovels

src/components/PrivateLayout/PrivateLayout.tsx
=> added a report button for the deputy #1567

src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx, src/pages/Documents/DocumentsTable.tsx, src/pages/Regions/RegionAdministration.tsx, src/pages/userPage/Approvers/Approvers.tsx, src/pages/userPage/Blanks/Blanks.tsx
+ fixed bugs 
[Річні звіти/ Annual reports] “Заступник Голови Округи/Станиці/Куреня” has not possible to create the “Річний звіт округи” #1509
[Repository/Репозитарій] “Заступник Голови Округи/Станиці/Куреня” has not possible to add the document #1510
+added confirmation window on deleting user from Region administration
[Profile/Blank] 'Заступник Голови куреня/станиці/округи' should have a possibility to modify the documents under 'Бланки' for users from the same hovel #1486
dev
ToDo
ToDo
ToDo
=> Fixed [Delegations/ Поручення] [City Admin] Delegations are not aligned on the "Поручення" tab #1569, other bugs #1509,#1510,1486

src/pages/AnnualReport/ClubAnnualReportForm/ClubAnnualReportForm.tsx, src/pages/Club/Club/Club.tsx, src/pages/Club/Club/ClubFollowers.tsx
=> #1468 Add possibility to cancel request for joining 

src/pages/Club/Club/Club.tsx, src/pages/Club/Club/ClubAdministration.tsx, src/pages/Club/Club/ClubDocuments.tsx
=> Fixed a few bugs on clubs

src/pages/Distinction/DistinctionTable/DeleteTypeConfirm.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/ActiveMembership/PlastDegree/DeleteDegreeConfirm.tsx, src/pages/userPage/Approvers/Approvers.tsx
=> Fix delegations

src/pages/Actions/ActionEvent/EventUser/EventUser.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/Approvers/Approvers.tsx, src/pages/userPage/Blanks/Blanks.tsx, src/pages/userPage/Secretaries/SecretariesPage.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx, src/pages/userPage/personalData/UserFields.tsx
=> #1552 Fix Failed request on user page

src/components/PrivateLayout/PrivateLayout.tsx
=> fix added reports to the menu  club depytty

src/pages/Club/CreateClub/CreateClub.tsx
=> #1532 Fix cursor disappeared

src/pages/City/Cities/Cities.less, src/pages/Club/Clubs/SortedClubs.tsx
=> Fixed bugs on hovel and region follower create button

src/pages/City/City/City.tsx, src/pages/City/City/CityFollowers.tsx
=> add possibility to cancel request for joining City#1468

src/pages/City/City/City.tsx, src/pages/Club/Club/Club.tsx, src/pages/Regions/Region.tsx
=> Added confirmation modal on head deputy change

src/pages/Documents/DocumentsTable.tsx, src/pages/Documents/columns.tsx, src/pages/RegionsBoard/RegionBoard.tsx, src/pages/userPage/Secretaries/columnsClubs.tsx
=> added tooltips#1588

src/models/City/CityProfile.tsx, src/models/Club/ClubProfile.tsx, src/models/Region/RegionProfile.tsx, src/pages/City/Cities/SortedCities.tsx, src/pages/City/City/City.tsx, src/pages/City/CreateCity/CreateCity.tsx, src/pages/Club/Club/Club.tsx, src/pages/Club/Clubs/SortedClubs.tsx, src/pages/Club/CreateClub/CreateClub.tsx, src/pages/Regions/AddRegion.tsx, src/pages/Regions/Region.tsx, src/pages/Regions/RegionEdit.tsx, src/pages/Regions/SortedRegions.tsx
=> Fixed bugs in Region, Clubs, Cities

src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
=> Fixed [Cities] As a deputy of city admin user couldn't add a degree of 'adherent' #1591

src/components/Notifications/Messages.tsx, src/pages/Actions/EventsModals.tsx, src/pages/City/AddDocumentModal/AddDocumentModal.tsx, src/pages/Club/AddDocumentModal/AddDocumentModal.tsx, src/pages/DecisionTable/FormAddDecision.tsx, src/pages/Documents/FormAddDocument.tsx, src/pages/GoverningBody/AddDocumentModal/AddDocumentModal.tsx, src/pages/GoverningBody/Sector/AddDocumentModal.tsx, src/pages/Regions/AddDocModal.tsx, src/pages/RegionsBoard/AddDocModal.tsx, src/pages/userPage/Blanks/UserAchievements/AddAchievementsModal.tsx, src/pages/userPage/Blanks/UserAchievements/ListOfAchievementsModal.tsx, src/pages/userPage/Blanks/UserBiography/AddBiographyModal.tsx, src/pages/userPage/Blanks/UserExtractFromUPU/AddExtractFromUPUModal.tsx
=> Fixed A long title of file is cut in the notifications, upload components (#1516)

src/pages/City/City/City.tsx, src/pages/Club/Club/Club.tsx, src/pages/Regions/AddRegionSecretaryForm.tsx, src/pages/Regions/Region.tsx
=> Fixed [Regions] We can see more than nine cities on page regions, more than six admins #1578

src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/City/CreateCity/CreateCity.tsx
=> Fixed bugs on edit city button and required index message, added some new notification after region follower creating

src/pages/Regions/Region.tsx
=> Fixed notification after deleting or editing region

src/pages/Regions/Region.tsx
=> Fixed region followers "more" button

src/pages/Regions/RegionAdministration.tsx
=> Fixed some code convention on region administration page

src/pages/userPage/Blanks/Blanks.tsx, src/pages/userPage/Blanks/UserAchievements/ListOfAchievementsModal.tsx
=> Added tooltips on blank

src/pages/City/Cities/SortedCities.tsx, src/pages/City/City/CityAdministration.tsx, src/pages/City/City/CityDocuments.tsx, src/pages/Club/Club/Club.tsx, src/pages/Club/Clubs/SortedClubs.tsx, src/pages/Regions/Region.tsx, src/pages/Regions/SortedRegions.tsx
=> Cities bugs

src/components/Notifications/Messages.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx, src/pages/Actions/ActionEvent/EventEdit/EventEdit.tsx, src/pages/DecisionTable/FormAddDecision.tsx, src/pages/DecisionTable/FormEditDecision.tsx, src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx, src/pages/Distinction/DistinctionTable/FormEditDistinction.tsx, src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx, src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx
=> Fixed bugs on Desicions/Precautions/Distinctions

src/models/Club/ClubProfile.tsx, src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/Club/Club/Club.tsx, src/pages/Club/ClubDetailDrawer/ClubDetailDrawer.tsx, src/pages/Club/CreateClub/CreateClub.tsx, src/pages/DecisionTable/FormEditDecision.tsx
=> Changes street to slogan for Hovel/Club

src/pages/City/City/CityAdministration.tsx, src/pages/Club/Club/Club.tsx, src/pages/Club/Club/ClubAdministration.tsx, src/pages/GoverningBody/GoverningBody/GoverningBodyAdministration.tsx, src/pages/GoverningBody/Sector/SectorAdministration.tsx, src/pages/Regions/RegionAdministration.tsx
=> Fixed [Провід] The system does not display the long job title completely #1641

src/pages/City/City/City.less, src/pages/Club/Club/Club.less, src/pages/GoverningBody/GoverningBody/GoverningBody.less, src/pages/GoverningBody/Sector/Sector.tsx, src/pages/Regions/Region.less, src/pages/Regions/Region.tsx, src/pages/Regions/RegionDocuments.tsx, src/pages/RegionsBoard/RegionBoardDocuments.tsx
=> Fixed [Documents] Alignment issue on a Country Documents tab #1240 an…d heigth in city/club/region followers,members,admins cards

src/pages/City/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/City/Cities/SortedCities.tsx, src/pages/City/City/City.tsx, src/pages/City/City/CityAdministration.tsx, src/pages/Club/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx, src/pages/Club/Club/Club.tsx, src/pages/Club/Clubs/SortedClubs.tsx, src/pages/Regions/AddAdministratorModal.tsx, src/pages/Regions/AddRegionSecretaryForm.tsx, src/pages/Regions/Region.tsx, src/pages/Regions/RegionAdministration.tsx, src/pages/Regions/SortedRegions.tsx
=> Fixed bug with admin modal and a few more

src/pages/GoverningBody/Announcement/Announcement.module.css, src/pages/GoverningBody/Announcement/Announcement.tsx, src/pages/GoverningBody/Announcement/Filter.less
=> fixed-lines

src/pages/DecisionTable/FormAddDecision.tsx, src/pages/UserTable/UserTable.tsx
=> Fixed fixed dropdown after clicking on another tab on User Table

src/pages/GoverningBody/CreateGoverningBody.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx
=> Fixed-one-bug-on-active-membership

src/pages/City/AddDocumentModal/AddDocumentModal.tsx, src/pages/Club/AddDocumentModal/AddDocumentModal.tsx, src/pages/GoverningBody/AddDocumentModal/AddDocumentModal.less
=> Fixed [Documents type on City/Hovel/Governing Bodies] section is shifted #1545

src/api/decisionsApi.tsx, src/pages/DecisionTable/FormAddDecision.tsx, src/pages/GoverningBody/GoverningBodyDetailDrawer.tsx, src/pages/GoverningBody/Sector/SectorDetailDrawer.tsx, src/pages/userPage/Approvers/Approvers.tsx
=> Fixed vouching for Plast Member and added some new roles to vouch. Fixed size for details on Governing Body. Fixed "Confirmed" field

src/pages/userPage/EditUserPage/EditUserPage.tsx
=> Changed min avilable birthday for user

src/components/Notifications/Messages.tsx, src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCreate.module.css, src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx, src/pages/Actions/ActionEvent/EventEdit/EventEdit.module.css, src/pages/Actions/ActionEvent/EventEdit/EventEdit.tsx, src/pages/DecisionTable/FormAddDecision.tsx, src/pages/DecisionTable/FormEditDecision.tsx, src/pages/GoverningBody/AddDocumentModal/AddDocumentModal.less
=> Modified add/edit event modals + fixed bugs connected to them

src/pages/Regions/Region.tsx
=> fixed notification after region unachivation

src/api/regionsApi.tsx, src/models/GllobalValidations/DescriptionValidation.tsx
=> Added new changes for exists region name validator

src/components/Notifications/Messages.tsx, src/pages/Actions/ActionEvent/EventUser/EventUser.module.css, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/EditUserPage/EditUserPage.tsx
=> Fixed [Access levels] Access levels are not aligned on page "Дійсне членство" in mobile#1694

src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCreate.module.css, src/pages/Actions/ActionEvent/EventEdit/EventEdit.module.css, src/pages/City/CreateCity/CreateCity.tsx, src/pages/Club/CreateClub/CreateClub.tsx, src/pages/GoverningBody/CreateGoverningBody.tsx, src/pages/GoverningBody/Sector/CreateSector.tsx, src/pages/GoverningBody/Sector/EditSector.tsx
=> Fixed [Country/Governing Bodies/City/Hovels] message about creation/edit appears twice #1647, added mandatory field on appeal

src/pages/SignIn/SignIn.tsx
=> Fixed start page after logging in

src/pages/Club/Club/Club.tsx
=> Created notification about removing from the club

src/pages/City/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/City/City/CityAdministration.tsx, src/pages/City/City/CityMembers.tsx, src/pages/Club/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/GoverningBody/GoverningBody/GoverningBodyAdministration.module.css, src/pages/GoverningBody/GoverningBody/GoverningBodyAdministration.tsx, src/pages/GoverningBody/Sector/SectorAdministration.tsx, src/pages/Regions/AddAdministratorModal.tsx, src/pages/UserTable/ChangeUserCityModal.tsx
=> Fixed bug with different icons and styling on Administation of governing body/sector

src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx, src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportTable.tsx
=> Fixed [Annual reports] Deputy of Region/City Admin can't view annual reports of any city/region/hovel. #1601

src/api/activeMembershipApi.ts, src/components/PrivateLayout/PrivateLayout.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx, src/pages/userPage/ActiveMembership/PlastDegree/ModalAddPlastDegree.tsx
=> Refactored code due to changed relations between user and userPlastDegrees (one user - one plast degree)

src/components/Notifications/Modals.tsx, src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/Regions/AddRegion.tsx, src/pages/Regions/RegionEdit.tsx
=> Made correct funcionality for checking region name

src/components/Notifications/Messages.tsx, src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.module.css, src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.tsx, src/pages/City/City/City.tsx, src/pages/Club/Club/Club.tsx, src/pages/Regions/Region.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx, src/pages/userPage/Approvers/Approvers.tsx, src/pages/userPage/Blanks/UserAchievements/AddAchievementsModal.tsx
=> Fixed several bugs (#1727,#1726,#1723, ...)

src/api/authorizeApi.ts, src/components/Notifications/Modals.tsx
=> Added info modal after trying to login as former member

src/pages/Regions/Region.tsx, src/pages/Regions/RegionFollowers.tsx
=> Fixed conditions for approving region followers

src/pages/Regions/AddRegion.tsx, src/pages/Regions/RegionEdit.tsx
=> Fixed some bug with checking of server response

src/pages/userPage/Blanks/Blanks.tsx
=> fixed access levels on Blanks for plast member

src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/City/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx, src/pages/Club/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx, src/pages/Documents/FormAddDocument.tsx, src/pages/Regions/AddAdministratorModal.tsx, src/pages/Regions/AddRegionSecretaryForm.tsx
=> Fixed [City/Hovel/Region] no name position can be assigned to a user #1755

src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/GoverningBody/CreateGoverningBody.tsx, src/pages/GoverningBody/Sector/CreateSector.tsx, src/pages/GoverningBody/Sector/EditSector.tsx
=> Fixed mandatory fields

src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.tsx, src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx
=> Access for admin to subscibe on event details form

src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.tsx
dev
changed name of button
ToDo
ToDo
ToDo
=> Renamed 'Сьогодні' button in FullCalendar(Events)

src/pages/Actions/ActionEvent/EventCard/EventCard.tsx, src/pages/Actions/ActionEvent/EventInfo/FormAddPictures.tsx, src/pages/City/City/City.tsx, src/pages/Club/Club/Club.tsx
=> Added a few impovements (events, city,club)

src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx
=> restrict adding lowrole users to admin

src/pages/UserTable/ChangeUserCityModal.tsx, src/pages/UserTable/ChangeUserRegionModal.tsx
=> Fix wrong error message (bug 1745)

src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/DecisionTable/FormAddDecision.tsx
=> Access to start text from a new line(textarea fields)

src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx, src/pages/Distinction/DistinctionTable/FormEditDistinction.tsx, src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx, src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx
=> Fixed [Award] [Precaution] have dynamic fields #1736 and #1797

src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/GoverningBody/CreateGoverningBody.tsx, src/pages/GoverningBody/Sector/CreateSector.tsx
=> Samename validator fix for gbs and sectors

src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.tsx, src/pages/userPage/EditUserPage/EditUserPage.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx, src/pages/userPage/personalData/PersonalData.less, src/pages/userPage/personalData/UserFields.tsx
=> Fix user page (Fixed next bugs #1634 #1721 #1719 )

src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.tsx, src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx
=> Access fro admin to approve himself as a participant

src/pages/UserTable/UserTable.module.css, src/pages/UserTable/UserTable.tsx
#1800 about 'OK' button alligning and #1684 about items sliding down in filter search
dev
ToDo
ToDo
ToDo
=> Fix bugs #1800 and #1684 in User Table

src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.tsx
=> Fix active membership  bugs #1634 #1724

src/api/governingBodiesApi.tsx, src/pages/GoverningBody/Announcement/AddAnnouncementModal.tsx, src/pages/GoverningBody/Announcement/Announcement.tsx, src/pages/GoverningBody/Announcement/DropDownAnnouncement.tsx, src/pages/GoverningBody/Announcement/EditAnnouncementModal.tsx
=> Added announcement editing

src/App.less, src/components/Header/Header.module.css, src/pages/userPage/personalData/PersonalData.less
=> Fix CSS styles (fixed bugs #1481 #1495 #1761)

src/pages/AnnualReport/AnnualReportTable/AnnualReportInformation/AnnualReportInformation.less
=> Unselectable stamp #1752

src/App.tsx, src/models/GoverningBody/GoverningBodyAnnouncement.tsx, src/pages/GoverningBody/Announcement/Announcement.tsx, src/pages/GoverningBody/Announcement/DropDownAnnouncement.tsx, src/pages/GoverningBody/GoverningBody/GoverningBody.tsx, src/pages/GoverningBody/Sector/Sector.tsx
=> Fixed announcement access and display

src/pages/Actions/EventTypes/EventTypes.module.css, src/pages/Actions/EventTypes/EventTypes.tsx, src/pages/Contacts/Contacts.tsx, src/pages/DecisionTable/FormAddDecision.tsx, src/pages/Regions/Region.tsx
=> Fixed several bugs #1826,#1809,#1807,#1795

src/components/Header/Header.module.css
=> Delete wrong style in Header.module.css (revert)

src/pages/RegionsBoard/RegionBoard.tsx
=> Fixed decision display

src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/GoverningBody/CreateGoverningBody.tsx, src/pages/GoverningBody/Sector/CreateSector.tsx, src/pages/GoverningBody/Sector/EditSector.tsx
=> Fixed samename validator

src/pages/Actions/ActionEvent/EventUser/EventUser.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/Approvers/Approvers.tsx, src/pages/userPage/Blanks/Blanks.tsx, src/pages/userPage/Secretaries/SecretariesPage.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx, src/pages/userPage/personalData/UserFields.tsx
=> Fix short profile (bug #1661)

src/pages/ResetPassword/ResetPassword.module.css, src/pages/SignIn/SignIn.module.css, src/pages/userPage/Approvers/Approvers.tsx
=> Fixed bugs #1749,1737,1759

src/components/PrivateLayout/PrivateLayout.tsx
=> Fixed highlighted items in left menu ( Fix bug #1534)

src/pages/AnnualReport/ClubAnnualReportForm/ClubAnnualReportTableColumns.tsx
=> bug fixes with club report display

src/api/governingBodySectorsApi.tsx, src/pages/userPage/Secretaries/SecretariesPage.tsx, src/pages/userPage/Secretaries/SecretaryModel.tsx, src/pages/userPage/Secretaries/UserSectorSecretaryTable.tsx, src/pages/userPage/Secretaries/columnsSectors.tsx
=> Added sector admin display in profile

src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/Interface/Interface.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx, src/pages/userPage/personalData/PersonalData.tsx
=> Added to context provider image to avoid multiple requests for the same image in UserPage

manifests/deployment.yml
=> Update resource limits and replica count

src/pages/UserTable/UserTable.tsx
=> Fix bug #1901 (search field length)

src/pages/AnnualReport/RegionAnnualReportForm/RegionAnnualReportForm.less
dev
ToDo
changed height value for labels from px to %
ToDo
=> Fix for bug #1834

src/pages/userPage/ActiveMembership/ActiveMembership.module.css, src/pages/userPage/personalData/PersonalData.less
=> Fix user profile styles (Fix bug #1883)

src/pages/AnnualReport/ClubAnnualReportForm/ClubAnnualReportForm.less, src/pages/AnnualReport/ClubAnnualReportForm/ClubAnnualReportForm.tsx
dev
ToDo
Fixed bug with fields overflow
ToDo
ToDo
=> fixed bug with elements overflow #1900

src/pages/userPage/ActiveMembership/ActiveMembership.tsx
=> Country, City and Hovel Admin can view 'Дійсне членство' of the registered user's profile (Fixes bug #1932)

src/pages/AnnualReport/RegionAnnualReportForm/RegionAnnualReportForm.less, src/pages/AnnualReport/RegionAnnualReportForm/RegionAnnualReportForm.tsx
=> Region annual report form title overflow

src/pages/AnnualReport/AnnualReportTable/AnnualReportInformation/AnnualReportInformation.less, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReportInformation/ClubAnnualReportInformation.less, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReportInformation/ClubAnnualReportInformation.tsx
=> Club annual report information elements overflow

src/pages/GoverningBody/AddDocumentModal/AddDocumentModal.tsx, src/pages/GoverningBody/Sector/AddDocumentModal.tsx, src/pages/RegionsBoard/AddDocModal.tsx
=> FIxed bug with document (#1927)

src/pages/Actions/ActionEvent/EventUser/EventUser.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.module.css, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/personalData/PersonalData.less, src/pages/userPage/personalData/UserFields.tsx
dev
Removed not needed imports. 
Added initial state for user dates in case of fetch dates will fail. 
Fixed style of user profile and bug with short profile.
ToDo
ToDo
ToDo
=> Fix user profile bugs (Fixes #1991 #1977)

src/pages/UserTable/UserTable.tsx
=> Fix filter clear

src/components/Header/Header.module.css, src/index.css
=> Fixed elements go beyond when narrow the page (Fixes #1884)

src/pages/UserTable/UserTable.tsx
=> Fix using two filters at the same time

src/pages/UserTable/DropDownUserTable.tsx, src/pages/UserTable/DropdownItem.tsx
=> Comments for context menu ut

src/api/citiesApi.tsx, src/api/regionsApi.tsx, src/config.ts, src/pages/City/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx, src/pages/City/City/City.tsx, src/pages/Club/Club/Club.tsx, src/pages/Regions/Region.tsx
=> add user access

src/components/Notifications/Messages.tsx, src/pages/City/Cities/SortedCities.tsx, src/pages/City/City/City.tsx, src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx, src/pages/Club/Club/Club.tsx, src/pages/Club/Clubs/SortedClubs.tsx, src/pages/Regions/Region.tsx, src/pages/Regions/SortedRegions.tsx
=> Regions cities clubs bugs

src/api/activeMembershipApi.ts, src/pages/UserTable/ChangeUserRoleForm.tsx, src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.tsx
=> Only oath date could be changed now (fix #1843)

src/pages/UserTable/UserTable.tsx
=> Fix filter items deselect

src/pages/City/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/City/City/City.tsx
=> add checking

src/pages/City/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx
=> add diasbled

src/pages/Actions/ActionEvent/EventInfo/PicturesWall.tsx, src/pages/City/CreateCity/CreateCity.tsx, src/pages/GoverningBody/GoverningBodies.tsx, src/pages/RegionsBoard/RegionBoard.tsx
[Крайовий провід] Incorrect name of the 'Керівні Органи' field #1949
[City] Make a limit of 5 characters and the message "Максимальна довжина - 5 символів" in the 'Поштовий індекс' field when you want to edit or create the city #2047
dev
ToDo
ToDo
ToDo
=> Fixed several bugs #1949,#2047,#1892

src/api/distinctionApi.tsx, src/pages/Distinction/DistinctionTable/DistinctionTable.tsx
=> Improve user access for distinctions

src/pages/Club/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/Regions/AddAdministratorModal.tsx
=> edit messages

src/pages/userPage/EditUserPage/EditUserPage.tsx
=> Fixed UI bugs of EditUserPage

src/pages/userPage/Approvers/Approvers.less
=> Fixed approvers cards style ( Fix bug #2013)

src/pages/City/City/City.tsx, src/pages/Club/Club/Club.tsx
=> Add new function SetAdmins

src/pages/City/CreateCity/CreateCity.tsx, src/pages/Club/CreateClub/CreateClub.tsx, src/pages/Regions/AddRegion.tsx, src/pages/Regions/RegionEdit.tsx
=> add loading for button edit/add hovel/city/reagion

src/pages/AnnualReport/AnnualReportTable/ClubAnnualReportInformation/ClubAnnualReportInformation.less, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReportInformation/ClubAnnualReportInformation.tsx
=> Fixed card height in Annual report

src/pages/Distinction/DistinctionTable/FormEditDistinctionTypes.tsx
=> Fixing bug with adding empty distinctions types

src/pages/City/City/CheckActiveMembersForm.tsx, src/pages/City/City/City.tsx, src/pages/Club/Club/CheckActiveMembersForm.tsx, src/pages/Club/Club/Club.tsx, src/pages/Regions/CheckActiveCitiesForm.tsx
Warning after trying to archive region with region's adherents, members or board now displays more user-friendly information
ToDo
ToDo
ToDo
=> Warning update 

src/components/Footer/Footer.module.css, src/pages/SignIn/SignIn.module.css, src/pages/SignUp/SignUp.module.css
=> Fix double click highlighted fielgs on Sign in page

src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/ConfirmedDropdown/ConfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/UnconfirmedDropdown/UnconfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/ConfirmedDropdown/ConfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/UnconfirmedDropdown/UnconfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/ConfirmedDropdown/ConfirmedRegionDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/UnconfirmedDropdown/UnconfirmedRegionDropdown.tsx
=> Fixed dropdown module in Annual Reports

src/pages/City/City/City.tsx
=> remove loading

src/pages/AnnualReport/ClubAnnualReportForm/ClubAnnualReportForm.tsx
=> Added mandatory asterisks in creating Club Annual Report

src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.module.css, src/pages/Actions/ActionEvent/EventUser/EventUser.module.css, src/pages/Actions/ActionEvent/EventUser/EventUser.tsx
=> Fixed buttons on events and calendar#1698

src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx
=> fixed selecting users in event creation #1925

src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx, src/pages/Actions/ActionEvent/EventEdit/EventEdit.tsx, src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx, src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.tsx
=> added notifications when changing participation status in event #2080

src/pages/DecisionTable/FormAddDecision.tsx, src/pages/Documents/FormAddDocument.tsx, src/pages/KadraVykhovnykiv/AddNewKadraForm.tsx, src/pages/KadraVykhovnykiv/UpdateKadraForm.tsx
=> fixed date entry error

src/pages/Actions/ActionEvent/EventInfo/EventDetails.less, src/pages/Actions/ActionEvent/EventInfo/EventInfo.less, src/pages/Actions/ActionEvent/EventInfo/FormAddPictures.tsx, src/pages/Actions/ActionEvent/EventInfo/Gallery.tsx
=> Fixed event galary and event description #1989

src/config.ts, src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx, src/pages/City/City/City.tsx, src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx, src/pages/Club/Club/Club.tsx, src/pages/Regions/AddRegionSecretaryForm.tsx, src/pages/Regions/Region.tsx
=> add new setAdmins

src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx, src/pages/Actions/ActionEvent/EventUser/EventUser.tsx
=> Accesses for editing event

src/api/KadraVykhovnykivApi.tsx, src/pages/KadraVykhovnykiv/Types/EducatorsStaffTableData.ts
=> Added API function and proper type for EducatorsStaff table (partially covers issue #2117)

src/api/citiesApi.tsx, src/api/clubsApi.tsx, src/pages/City/City/City.tsx, src/pages/Club/Club/Club.tsx, src/pages/Regions/Region.tsx
=> Delete yourself bug fixed

src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx
=> made admin card clickable

src/components/Notifications/Messages.tsx, src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx
=> Changed messages in notifications after confirm or cancel annual report

src/pages/DecisionTable/DecisionTable.tsx
=> fixed deleting decision

src/pages/SignUp/SignUp.tsx
=> Add modal confirm for agreement with terms

src/pages/SignUp/SignUp.tsx
=> Fixed agreement terms

src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/CitySelectModal/CitySelectModal.less, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/ConfirmedDropdown/ConfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/SavedDropdown/SavedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/UnconfirmedDropdown/UnconfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/ConfirmedDropdown/ConfirmedRegionDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/SavedDropdown/SavedRegionDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/UnconfirmedDropdown/UnconfirmedRegionDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportTable.tsx
=> Fixed that modal menu was out screen and mobile bug #2020

src/api/decisionsApi.tsx, src/models/Documents/DocumentPost.tsx, src/models/Documents/DocumentsTableInfo.tsx, src/pages/DecisionTable/DropDownDecision.tsx, src/pages/DecisionTable/FormAddDecision.tsx, src/pages/DecisionTable/Interfaces/DecisionTableInfo.tsx, src/pages/Documents/DropDownDocuments.tsx, src/pages/Documents/FormAddDocument.tsx, src/pages/KadraVykhovnykiv/AddNewKadraForm.tsx
=> fixed the date entry bug

src/pages/SignUp/Switcher/Switcher.module.css
=> Fixed sign in and sign up buttons (fixes bug #1758)

src/models/AnnualReport/ReportStatus.ts, src/models/AnnualReport/ReportType.ts, src/pages/AnnualReport/ClubAnnualReportEdit/ClubAnnualReportEdit.tsx
=> fixed access for club edit page

src/pages/SignUp/SignUp.tsx
=> Fixed modal confirm with terms

src/App.tsx, src/components/Notifications/Messages.tsx, src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/City/City/City.tsx, src/pages/Club/Club/Club.tsx, src/pages/GoverningBody/CreateGoverningBody.tsx, src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
=> Fixed two bugs

src/api/governingBodiesApi.tsx, src/pages/userPage/Secretaries/SecretaryModelForTable.ts, src/pages/userPage/Secretaries/UserGoverningBodySecretaryTable.tsx, src/pages/userPage/Secretaries/columnsGoverningBodies.tsx
=> Updated GoverningBodiesTable (covers Bug #2167)

src/components/ButtonCollapse/ButtonCollapse.module.css, src/components/ButtonCollapse/ButtonCollapse.tsx, src/pages/DecisionTable/AddDecisionModal.tsx, src/pages/DecisionTable/DecisionTable.tsx, src/pages/DecisionTable/FormAddDecision.tsx, src/pages/DecisionTable/FormEditDecision.tsx, src/pages/KadraVykhovnykiv/AddNewKadraForm.tsx, src/pages/KadraVykhovnykiv/DeleteConfirm.tsx, src/pages/KadraVykhovnykiv/KVTable.tsx, src/pages/KadraVykhovnykiv/KadraDropDown.tsx, src/pages/KadraVykhovnykiv/KadrasPage.tsx
=> Fixed delete on Kadra

src/pages/SignUp/SignUp.tsx
=> Fixed spinner

src/pages/AnnualReport/AnnualReportEdit/AnnualReportEdit.tsx, src/pages/AnnualReport/AnnualReportForm/AnnualReportForm.tsx
=> Fix validation in edit annual report form

src/api/governingBodySectorsApi.tsx, src/pages/userPage/Secretaries/SectorModelForTable.ts, src/pages/userPage/Secretaries/UserSectorSecretaryTable.tsx, src/pages/userPage/Secretaries/columnsSectors.tsx
=> Updated sector table

src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx, src/pages/GoverningBody/CreateGoverningBody.tsx
=> User duplication bug fixed

src/components/PrivateLayout/PrivateLayout.tsx, src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx
=> Changed view annual reports due to accesses

src/pages/Distinction/DistinctionTable/FormEditDistinction.tsx, src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx
=> fixed bag on edit form

src/pages/City/CreateCity/CreateCity.tsx
=> add data for edit

src/pages/DecisionTable/FormAddDecision.tsx, src/pages/DecisionTable/FormEditDecision.tsx
=> used getPopupContainer property in mentions

src/pages/City/City/CityFollowers.tsx, src/pages/City/CreateCity/CreateCity.tsx, src/pages/Club/Club/ClubFollowers.tsx
=> fix add to member in CityFollowers

src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx, src/pages/City/City/CityAdministration.tsx
=> add userAccesses

src/pages/UserTable/ChangeUserRoleForm.tsx, src/pages/UserTable/ChangeUserRoleModal.tsx
=> UserTableFields reset on cancel, finish and closing ChangeUserModal window

src/pages/UserTable/ChangeUserRoleForm.tsx
=> Modified ChangeUserRoleForm (related to Bug#2171)

src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx
=> Users for precautions

src/components/PrivateLayout/PrivateLayout.tsx, src/models/UserAccess/IUserAccess.ts, src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/ConfirmedDropdown/ConfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/SavedDropdown/SavedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/UnconfirmedDropdown/UnconfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/ConfirmedDropdown/ConfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/SavedDropdown/SavedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/UnconfirmedDropdown/UnconfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/ConfirmedDropdown/ConfirmedRegionDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/SavedDropdown/SavedRegionDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/UnconfirmedDropdown/UnconfirmedRegionDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportTable.tsx
=> Fixed accesses for viewing annual reports

src/api/activeMembershipApi.ts, src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.tsx
=> Returned possibility to change entry date (Fix #1843)

src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx
=> Fixed viewing annual reports table with two or more roles

src/pages/City/Cities/ActionCities.tsx, src/pages/City/Cities/SortedCities.tsx, src/pages/Club/Clubs/SortedClubs.tsx, src/pages/Regions/SortedRegions.tsx
=> Fixed return to previous page bug

src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.tsx, src/pages/userPage/personalData/PersonalData.tsx
=> Fixed bug with editing single Entry date #1843

src/pages/KadraVykhovnykiv/UpdateKadraForm.tsx
=> Kadra edit form

src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx
=> Fix bug with calendar

src/pages/KadraVykhovnykiv/KadrasPage.tsx
=> get kadra type id from db

src/pages/RegionsBoard/AddDocModal.tsx
=> Recrudescent document upload is now enabled

src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx, src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
=> Announcement is now added to announcements without refreshing the page

src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.tsx
=> [Events] No confirmation window appears when rejecting a participant from the event #2245

src/App.tsx, src/components/ScrollToTop/ScrollToTop.tsx, src/pages/userPage/Approvers/Approvers.tsx, src/pages/userPage/personalData/PersonalData.tsx
=> Fixed bug with button reject approve and fixed bug with scroll #2182

src/pages/Statistics/StatisticsCities.tsx, src/pages/Statistics/StatisticsRegions.tsx
=> Fixed Statistics bug in Cities and Regions with disabled fields

src/models/PDF/AnnualReport/CityAnnualReportLayout.tsx, src/models/PDF/AnnualReport/ClubAnnualReportLayout.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx, src/pages/AnnualReport/AnnualReportTable/ClubAnnualReportInformation/ClubAnnualReportInformation.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/ConfirmedDropdown/ConfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/ConfirmedDropdown/ConfirmedDropdownProps.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/SavedDropdown/SavedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/SavedDropdown/SavedDropdownProps.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/UnconfirmedDropdown/UnconfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/UnconfirmedDropdown/UnconfirmedDropdownProps.tsx, src/pages/AnnualReport/Interfaces/ClubAnnualReport.ts
=> Club annual report pdf

src/api/precautionApi.tsx, src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx
=> Error message on adding the same precaution

src/pages/SignUp/SignUp.tsx
=> Fixed alignment text of terms

src/models/PDF/Decision/DecisionLayout.tsx, src/pages/DecisionTable/DropDownDecision.tsx
=> Fixed pdf on decision

src/api/UserApi.tsx, src/components/PrivateLayout/PrivateLayout.tsx
=> Accesses for menu

src/pages/AboutBase/FormAddSubsection.tsx
=> fixed bug with adding pictures

src/components/PrivateLayout/PrivateLayout.tsx
=> Updated menu accesses

src/pages/Distinction/DistinctionTable/DeleteConfirm.tsx, src/pages/Distinction/DistinctionTable/DistinctionTable.tsx, src/pages/Distinction/DistinctionTable/columns.tsx, src/pages/Precaution/PrecautionTable/PrecautionTable.tsx
=> Precautions table settings

src/models/PDF/Decision/DecisionLayout.tsx
=> Fixed date pdf decision

src/pages/AnnualReport/AnnualReportForm/AnnualReportForm.tsx
=> Add asterisks to mandatory fields in CreateCityAnnualReport

src/api/KadraVykhovnykivApi.tsx, src/pages/KadraVykhovnykiv/Interfaces/KadraTableSettings.ts, src/pages/KadraVykhovnykiv/KVTable.tsx, src/pages/KadraVykhovnykiv/columns.tsx, src/pages/Precaution/PrecautionTable/Table.module.css
=> Kadra table fixed sorting

src/pages/Statistics/StatisticsCities.tsx, src/pages/Statistics/StatisticsRegions.tsx
=> Fixed clearing chart on statistics

src/api/decisionsApi.tsx, src/pages/DecisionTable/DecisionTable.tsx, src/pages/DecisionTable/DropDownDecision.tsx, src/pages/DecisionTable/EditDecisionModal.tsx, src/pages/DecisionTable/FormAddDecision.tsx, src/pages/DecisionTable/FormEditDecision.tsx
=> Fixed decision add edit

src/pages/Statistics/StatisticsCities.less, src/pages/Statistics/StatisticsCities.tsx, src/pages/Statistics/StatisticsRegions.less, src/pages/Statistics/StatisticsRegions.tsx
=> Add message how to create chart on statistics

src/pages/Actions/ActionEvent/EventInfo/EventDetails.less, src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.tsx, src/pages/Actions/ActionEvent/EventInfo/EventInfo.less, src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx
=> Merged 2 components on event page fixed responsiveness

src/api/adminApi.tsx, src/pages/UserTable/ChangeUserRoleForm.tsx
=> add notification

src/pages/AnnualReport/RegionAnnualReportForm/RegionAnnualReportForm.tsx
=> Add validation in creating region annual report

src/pages/AnnualReport/ClubAnnualReportForm/ClubAnnualReportForm.tsx
=> Remove numeric input in creating club annual report

src/api/adminApi.tsx, src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/DecisionTable/FormAddDecision.tsx
=> Fixed target decision validation

src/pages/userPage/EditUserPage/EditUserPage.tsx
=> Fixed #2304

src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx
=> Changes in EventCreate file - in Date Picker

src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/AnnualReport/AnnualReportForm/AnnualReportForm.less, src/pages/AnnualReport/AnnualReportForm/AnnualReportForm.tsx, src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx
=> Fixed #2334 #2159 #2344

src/config.ts, src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx, src/pages/Documents/FormAddDocument.tsx
=> Event create alternate

src/pages/UserTable/ColumnsForUserTable.tsx
=> add options to filter

src/config.ts, src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCreateDrawer.tsx, src/pages/UserTable/ColumnsForUserTable.tsx
=> No more required questions while creating event; Changed "x" on "-" in event form

src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
=> City Admin can assign any degree to members

src/api/regionsApi.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCreateDrawer.tsx, src/pages/Actions/ActionEvent/EventEdit/EventEdit.tsx, src/pages/Actions/ActionEvent/EventEdit/EventEditDrawer.tsx, src/pages/Regions/RegionAdministration.tsx
- fixed button "X"
- fixed button "Cancel"
- fixed selection of already selected users
dev
ToDo
ToDo
ToDo
=> Fixes of event editing form

src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.less, src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.tsx
=> Clicked button turns disabled without ability to be pressed again - bug #2246

src/pages/City/AddDocumentModal/AddDocumentModal.tsx, src/pages/Club/AddDocumentModal/AddDocumentModal.tsx, src/pages/GoverningBody/AddDocumentModal/AddDocumentModal.tsx, src/pages/GoverningBody/Sector/AddDocumentModal.tsx, src/pages/Regions/Form.module.css, src/pages/RegionsBoard/AddDocModal.tsx
=> [Regional Board of the Plast/City/Hovel/Region] aligning changes after entering an empty spaces #2329

src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.module.css, src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.tsx, src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.tsx
=> Buttons in modal

src/pages/userPage/ActiveMembership/ActiveMembership.tsx
=> change access kurinhead

src/api/governingBodiesApi.tsx, src/models/Roles/AdminRole.tsx, src/models/Roles/Roles.tsx, src/models/UserTable/DropdownFunc.tsx, src/pages/UserTable/ChangeUserGoverningBodyForm.tsx, src/pages/UserTable/ChangeUserGoverningBodyModal.tsx, src/pages/UserTable/DeleteGoverningBodyAdminForm.tsx, src/pages/UserTable/DeleteGoverningBodyAdminModal.tsx, src/pages/UserTable/DropDownUserTable.tsx, src/pages/UserTable/DropdownItem.tsx, src/pages/UserTable/UserTable.tsx
=> Organization admin(GoverningBodyAdmin) added items to DropDown in UserTable

src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx
=> Сoma cannot be placed in the field #2406

src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.tsx, src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx, src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx
=> Fixing lopping events requests

src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.tsx, src/pages/Actions/ActionEvent/EventEdit/EventEdit.tsx, src/pages/Regions/Region.tsx, src/pages/Regions/RegionFollowers.tsx
=> Comma input edit event

src/pages/GoverningBody/Announcement/AddAnnouncementModal.tsx, src/pages/GoverningBody/Announcement/Announcement.tsx, src/pages/GoverningBody/Announcement/EditAnnouncementModal.tsx, src/pages/GoverningBody/Announcement/FormAddAnnouncement.tsx, src/pages/GoverningBody/GoverningBody/GoverningBody.tsx, src/pages/GoverningBody/Sector/Sector.tsx, src/pages/GoverningBody/Sector/SectorAnnouncement/AddAnnouncementModal.tsx, src/pages/GoverningBody/Sector/SectorAnnouncement/EditAnnouncementModal.tsx, src/pages/GoverningBody/Sector/SectorAnnouncement/FormAddAnnouncement.tsx, src/pages/GoverningBody/Sector/SectorAnnouncement/SectorAnnouncement.tsx
=> Empty announcements fixed

src/models/GllobalValidations/DescriptionValidation.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx, src/pages/Actions/ActionEvent/EventEdit/EventEdit.tsx, src/pages/Actions/ActionEvent/EventInfo/EventDetails.less, src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.less, src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.tsx, src/pages/Actions/ActionEvent/EventInfo/EventInfo.less
=> User can input active link to the Location field

src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.less, src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.tsx, src/pages/UserTable/UserTable.tsx
=> User can input active link to the Location field - update

src/pages/Actions/ActionEvent/EventInfo/FormAddPictures.tsx
=> When loaded photos are deleted button becomes disabled

src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.less, src/pages/UserTable/ColumnsForUserTable.tsx
=> Change align sorting arrows #1459

src/pages/Actions/ActionEvent/EventInfo/EventInfo.less, src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx, src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx
=> Fixing bug 2405

src/api/NotificationBoxApi.tsx
=> Fix bug 2143

src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx, src/pages/userPage/ActiveMembership/PlastDegree/ModalAddPlastDegree.tsx
=> fix main bug

src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx, src/pages/Statistics/StatisticsCities.tsx, src/pages/Statistics/StatisticsRegions.tsx, src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
=> Popup notification

package-lock.json, src/pages/City/CreateCity/CreateCity.tsx, src/pages/Club/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/Club/Club/Club.tsx, src/pages/Club/CreateClub/CreateClub.tsx, src/pages/GoverningBody/Announcement/FormAddAnnouncement.tsx, src/pages/Regions/AddRegion.tsx
=> commit 2300 bug plus another

src/pages/Club/Club/Club.tsx
=> fixed bug 2408 and 2300 fixed mistake

src/pages/Actions/ActionEvent/EventEdit/EventEdit.tsx
=> fix problem with validator on disabled date

src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
=> Fix issue 2389

src/pages/City/Cities/SortedCities.tsx
=> Fix GBAdmin not being able to create city

src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportTable.tsx
=> fixed annual report button, bug#2292

src/components/Notifications/Messages.tsx, src/pages/Statistics/StatisticsCities.tsx, src/pages/Statistics/StatisticsRegions.tsx
=> Only form statistics based on approved reports

src/pages/City/CreateCity/CreateCity.tsx
[#2484](https://github.com/ita-social-projects/EPlast/issues/2484)
=> Fix CreateCity form not having data

src/pages/Statistics/StatisticsCities.tsx, src/pages/Statistics/StatisticsRegions.tsx
=> Statistics table fix and total column

src/components/Quill/FormWithQuill.css, src/pages/AnnouncementsTable/Forms/FormEditAnnouncement.tsx
Fix issue
https://github.com/ita-social-projects/EPlast/issues/2503
dev
ToDo
ToDo
ToDo
=> Fix issue #2503

src/components/Header/HeaderContainer.tsx
Fix issue #1481
https://github.com/ita-social-projects/EPlast/issues/1481
dev
ToDo
ToDo
ToDo
=> Fix issue #1481

src/pages/AnnouncementsTable/Forms/FormAddAnnouncement.tsx
Fix issue https://github.com/ita-social-projects/EPlast/issues/2542
dev
ToDo
ToDo
ToDo
=> Fix issue #2542

src/pages/City/AddAdministratorModal/AddAdministratorModal.tsx
Fix issue https://github.com/ita-social-projects/EPlast/issues/2216
dev
ToDo
ToDo
ToDo
=> Fix issue #2216

src/pages/RegionsBoard/RegionBoard.tsx
=> deleted Decisions from RegionsBoard

src/pages/DecisionTable/columns.tsx
=> Fix Issue #2519

src/models/GllobalValidations/DescriptionValidation.tsx
Closes ita-social-projects/EPlast#2529
=> Remove required rule from office number

src/pages/City/Cities/SortedCities.tsx, src/pages/Club/Clubs/SortedClubs.tsx, src/pages/Regions/SortedRegions.tsx
=> Fixing searching bug on Regions, Cities and Clubs 2299

src/pages/City/City/City.tsx, src/pages/Club/Club/Club.tsx
=> Add user table link to Club page for admins

src/pages/Club/AddAdministratorModal/AddAdministrationModal.less, src/pages/UserTable/ChangeUserRoleModal.less, src/pages/UserTable/ChangeUserRoleModal.tsx
=> Fixed buttons aligning #2515

src/config.ts, src/pages/City/CreateCity/CreateCity.tsx
=> Citieslevel

src/pages/City/City/City.tsx, src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
=> City user fix - spinner, loading user and his photo

src/pages/UserTable/ColumnsForUserTable.tsx
=> Changed arrows aligning on user table

src/pages/UserTable/UserTable.tsx
=> Update UserTable tab sorting

src/pages/Regions/RegionAdministration.tsx
Fix issue https://github.com/ita-social-projects/EPlast/issues/2012
dev
ToDo
ToDo
ToDo
=> Fix issue #2012

src/components/PrivateLayout/PrivateLayout.tsx, src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx, src/pages/Regions/Region.tsx
=> Refactoring - replace country with region naming

src/models/UserTable/DropdownFunc.tsx, src/pages/UserTable/DropDownUserTable.tsx, src/pages/UserTable/DropdownItem.tsx, src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
=> Delete accept to city item, instead here is 'Додати до уладу' and partial fix #2561

src/api/authorizeApi.ts, src/pages/SignUp/SignUp.tsx, src/pages/SignUp/Switcher/Switcher.module.css
=> Switcher styles

src/models/Region/RegionProfile.tsx, src/pages/Regions/AddRegion.tsx, src/pages/Regions/RegionEdit.tsx
[![](https://snipboard.io/Yn0UGb.jpg)](https://www.youtube.com/watch?v=Hrph2EW9VjY)
=> Fix Regions creation

src/models/UserTable/DropdownFunc.tsx, src/pages/UserTable/DropDownUserTable.tsx, src/pages/UserTable/DropdownItem.tsx
=> UserTable_UserAccess_Fix

src/App.less, src/pages/AnnouncementsTable/AnnouncementsTable.tsx, src/pages/City/City/CheckActiveMembersForm.less, src/pages/City/City/City.less, src/pages/City/City/City.tsx, src/pages/City/City/CityAdministration.tsx, src/pages/City/City/CityFollowers.tsx, src/pages/City/City/CityMembers.tsx, src/pages/Club/Club/Club.tsx, src/pages/GoverningBody/Announcement/Announcement.tsx, src/pages/GoverningBody/Sector/SectorAnnouncement/SectorAnnouncement.tsx, src/pages/UserTable/DropdownItem.tsx, src/pages/userPage/personalData/UserFields.tsx
=> default cursor for unregistered users

src/pages/SignUp/CheckboxsItem.tsx, src/pages/SignUp/verification.ts
=> surname fix

src/pages/City/CreateCity/CreateCity.tsx
=> Fix gutter

package-lock.json, src/pages/userPage/Menu/Menu.tsx, src/pages/userPage/personalData/Course.tsx, src/pages/userPage/personalData/PersonalData.less
=> add-link-on-list-certificates

src/pages/GoverningBody/GoverningBody/GoverningBody.less
=> Governing bodies Images object-fit contain 

src/api/citiesApi.tsx, src/models/UserTable/DropdownFunc.tsx, src/models/UserTable/UserTable.tsx, src/pages/GoverningBody/Sector/AddDocumentModal.tsx, src/pages/UserTable/ColumnsForUserTable.tsx, src/pages/UserTable/DeleteCityFollowerModal.less, src/pages/UserTable/DeleteCityFollowerModal.tsx, src/pages/UserTable/DropDownUserTable.tsx, src/pages/UserTable/DropdownItem.tsx, src/pages/UserTable/UserTable.module.css, src/pages/UserTable/UserTable.tsx
=> Add Remove Follower button to UserTable

src/components/Notifications/Messages.tsx, src/pages/City/City/City.tsx, src/pages/City/City/CityFollowers.tsx, src/pages/UserTable/DropDownUserTable.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx, src/pages/userPage/ActiveMembership/PlastDegree/ModalAddPlastDegree.tsx
=> Add degree modal fix

src/models/City/CityUser.tsx, src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx, src/pages/City/City/City.tsx, src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx, src/pages/Club/Club/Club.tsx, src/pages/GoverningBody/Sector/AddSectorAdminForm.tsx, src/pages/Regions/AddRegionSecretaryForm.tsx, src/pages/Regions/Region.tsx
=> Add email to user dropdown options

src/pages/City/Cities/SortedCities.tsx, src/pages/Club/Clubs/SortedClubs.tsx, src/pages/Regions/SortedRegions.tsx
Фікс на пагінацію на списках станиць, округ та куренів: при зміні розміру сторінки (з 10 на сторінці на 50 на сторінці) ми залишались на 3й сторінці
=> Fix pagination

src/pages/userPage/personalData/UserFields.tsx
Фікс що попередження "оберіть станицю" відображається на сторінці інших користувачів
=> Fix warning being shown on other's profile page

src/Routes.tsx, src/components/Breadcrumb/Breadcrumb.tsx
=> Fixed Links for Cities and Sectors

src/pages/UserTable/DropDownUserTable.tsx, src/pages/UserTable/DropdownItem.tsx
=> User Table context menu Add/Change Degree Fix

src/api/UserApi.tsx, src/pages/UserRenewal/UserRenewalTable/UserRenewalTable.tsx, src/pages/UserTable/UserTable.tsx, src/pages/userPage/personalData/PersonalData.tsx
=> Remove currentUserId parameter from User action

src/pages/SignUp/SignUp.tsx, src/pages/userPage/EditUserPage/EditUserPage.tsx, src/pages/userPage/personalData/UserFields.tsx
=> editUserPage validation

src/pages/Regions/Region.tsx
=> Remove width parameter on Region Provid modal

src/pages/UserTable/UserTable.tsx
Closes https://github.com/ita-social-projects/EPlast/issues/2660
=> Fix query loading on User Table

src/components/Notifications/Messages.tsx, src/pages/UserRenewal/UserRenewal.tsx
Closes https://github.com/ita-social-projects/EPlast/issues/2510
Coupled with https://github.com/ita-social-projects/EPlast/pull/2770
Closes https://github.com/ita-social-projects/EPlast/issues/2510
ToDo
ToDo
=> #2510 Fix Renewal Notification

src/pages/City/CreateCity/CreateCity.tsx, src/pages/Regions/Region.tsx, src/pages/Regions/RegionFollowers.tsx
Closes https://github.com/ita-social-projects/EPlast/issues/2764
Closes https://github.com/ita-social-projects/EPlast/issues/2487
Coupled with: https://github.com/ita-social-projects/EPlast/pull/2792
=> #2764 Fix City Application Access

src/pages/Regions/RegionAdministration.tsx
Closes: https://github.com/ita-social-projects/EPlast/issues/2744
Coupled with: https://github.com/ita-social-projects/EPlast/pull/2820
=> #2744 Fix region administration access

src/api/regionsApi.tsx, src/pages/Regions/RegionAdministration.tsx
I removed ChangeStatusAdministration{/Id} endpoint.
Now changing status is happening in Region Service in remove admin endpoint
ToDo
ToDo
ToDo
=> Fix deleting secretary role

src/pages/userPage/personalData/Courses.tsx
closes https://github.com/ita-social-projects/EPlast/issues/2663
dev
ToDo
ToDo
ToDo
=> Fix-#2663. Reduced distance between ui elements

src/pages/UserTable/ColumnsForUserTable.tsx, src/pages/UserTable/UserTable.module.css
Modified color of text in yellow tag element
closes https://github.com/ita-social-projects/EPlast/issues/2632
=> Fix-#2632. Improved text visibility

src/pages/City/City/City.tsx, src/pages/City/City/CityDocuments.tsx
closes https://github.com/ita-social-projects/EPlast/issues/2728
=> Fix-#2728. User could not see the full name of the document

src/pages/Club/AddAdministratorModal/AddAdministratorModal.tsx
Allowed to change end of administration date for earlier one
closes https://github.com/ita-social-projects/EPlast/issues/2819
dev
ToDo
ToDo
ToDo
=> Fix-#2819. The period of administration could not be changed for shorter while editing the role in hovel

src/models/AnnualReport/RegionAnnualReport.ts, src/pages/AnnualReport/AnnualReportMenu.tsx, src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportInformation.tsx, src/pages/AnnualReport/AnnualReportTable/RegionMembersTable/RegionMembersTable.tsx
fix access to RegionReport
dev
ToDo
ToDo
ToDo
=> fix-regionReportAccess

src/pages/AnnualReport/AnnualReportTable/Dropdowns/ConfirmedDropdown/ConfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/SavedDropdown/SavedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/Dropdowns/UnconfirmedDropdown/UnconfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/ConfirmedDropdown/ConfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/SavedDropdown/SavedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/UnconfirmedDropdown/UnconfirmedDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/ConfirmedDropdown/ConfirmedRegionDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/SavedDropdown/SavedRegionDropdown.tsx, src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/UnconfirmedDropdown/UnconfirmedRegionDropdown.tsx
Report Edit and View options visibility were fixed according to role restrictions
dev
ToDo
ToDo
ToDo
=> ReportEdit&ViewVisibilityFix

src/pages/GoverningBody/GoverningBody/GoverningBody.tsx, src/pages/GoverningBody/Sector/Sector.tsx
=> Set distant between elems

src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
=> Fix status name in the nonfocation

src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
closes: https://github.com/ita-social-projects/EPlast/issues/2674
dev
ToDo
ToDo
ToDo
=> 2674-fix-grammar-mistakes

src/pages/City/CreateCity/CreateCity.tsx, src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
closes https://github.com/ita-social-projects/EPlast/issues/2657
=> Fix-#2657. Notification texts improvement

src/pages/Actions/ActionEvent/EventUser/EventUser.module.css, src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx, src/pages/City/City/City.tsx, src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx, src/pages/Club/Club/Club.tsx, src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx, src/pages/GoverningBody/Sector/AddSectorAdminForm.tsx, src/pages/Regions/AddRegionSecretaryForm.tsx, src/pages/Regions/Region.tsx, src/pages/RegionsBoard/RegionBoard.tsx, src/pages/userPage/Blanks/Blanks.module.css, src/pages/userPage/personalData/Courses.tsx
Fix:
1. After adding new administrator modal will not close
2. Courses have width 100%
3. Some refactoring
Closes https://github.com/ita-social-projects/EPlast/issues/2766
ToDo
ToDo
ToDo
=> Fix add administrator modal logic and styles for block items

src/api/blankApi.tsx, src/models/Blank/BlankDocument.tsx, src/pages/userPage/Blanks/Blanks.tsx, src/pages/userPage/Blanks/UserAchievements/AddAchievementsModal.tsx, src/pages/userPage/Blanks/UserAchievements/ListOfAchievementsModal.tsx, src/pages/userPage/personalData/Courses.tsx, src/pages/userPage/personalData/PersonalData.less
Closes https://github.com/ita-social-projects/EPlast/issues/2664
Fixed:
1. 'Add Certificate' button (dis)appearing logic
2. Incorrect course logo and 'Add Certificate' displaying after decreasing browser width
3. Refresh achievments count after deleting some achiements in Blanks page
4. No achievements displayed after modal opened first time
ToDo
ToDo
ToDo
=> Fix 'Add Certificate' button (dis)appearing logic and much more

src/pages/City/City/CityAdministration.tsx, src/pages/City/City/CityDocuments.tsx, src/pages/Club/Club/ClubAdministration.tsx, src/pages/Club/Club/ClubDocuments.tsx, src/pages/GoverningBody/GoverningBody/GoverningBodyAdministration.tsx, src/pages/GoverningBody/GoverningBody/GoverningBodyDocuments.tsx, src/pages/GoverningBody/Sector/SectorAdministration.tsx, src/pages/GoverningBody/Sector/SectorDocuments.tsx, src/pages/Regions/RegionAdministration.tsx, src/pages/Regions/RegionDocuments.tsx, src/pages/RegionsBoard/RegionBoardDocuments.tsx
Closes https://github.com/ita-social-projects/EPlast/issues/2721
ToDo
ToDo
ToDo
=> Now buttons in administration and documents have tooltips

src/pages/City/City/City.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.module.css
Closes https://github.com/ita-social-projects/EPlast/issues/2559
ToDo
ToDo
ToDo
=> Fix pointer cursor on forbidden to click components for registered user

src/pages/Error/NotFound.tsx
=> Message modification

src/pages/UserTable/UserTable.module.css
closes https://github.com/ita-social-projects/EPlast/issues/2710
=> Issue #2710. Button sizes on user table page

src/api/userRenewalsApi.ts, src/models/UserTable/UserTable.tsx, src/pages/UserRenewal/UserRenewalTable/UserRenewalTable.tsx, src/pages/UserRenewal/UserRenewalTable/columns.tsx, src/pages/UserTable/ColumnsForUserTable.tsx
=> userTableNewColumnsAndFilter

src/pages/UserTable/ColumnsForUserTable.tsx
=> dateColumnsBug

src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx, src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.tsx
closes https://github.com/ita-social-projects/EPlast/issues/2929
=> Fix-#2929. Added the possibility for an admin to view users who applied for the event

src/pages/City/City/CityAdministration.tsx, src/pages/Club/Club/ClubAdministration.tsx, src/pages/Regions/RegionAdministration.tsx
Closes https://github.com/ita-social-projects/EPlast/issues/2832
Closes https://github.com/ita-social-projects/EPlast/issues/2931
ToDo
ToDo
ToDo
=> Remove edit button from (region/city/club) head

src/pages/UserTable/ColumnsForUserTable.tsx
=> returnDatesToTable

src/pages/ResetPassword/ResetPassword.module.css, src/pages/ResetPassword/ResetPassword.tsx
Closes: https://github.com/ita-social-projects/EPlast/issues/2808
ToDo
ToDo
ToDo
=> Fix incorrect ui displaying on reset password page

src/api/eventsApi.ts, src/components/Notifications/Messages.tsx, src/models/EventCreate/EventCategories.tsx, src/pages/Actions/ActionEvent/EventCategoriesEdit/EventCategoriesEdit.tsx, src/pages/Actions/ActionEvent/EventCategoriesEdit/EventCategoriesEditDrawer.tsx, src/pages/Actions/ActionEvent/EventCategoriesEdit/EventCategoriesEditFormValidators.ts, src/pages/Actions/ActionEvent/EventCategoriesEdit/EventCategoryEditForm.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCreate.module.css, src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCreateDrawer.tsx, src/pages/Distinction/DistinctionTable/FormEditDistinctionTypes/DistinctionTypeInputValidator.tsx, src/pages/Distinction/DistinctionTable/FormEditDistinctionTypes/FormListOfDistinctionTypes.tsx
Closes: https://github.com/ita-social-projects/EPlast/issues/2936
Coupled with: https://github.com/ita-social-projects/EPlast/pull/2942
ToDo
ToDo
ToDo
=> Added possibility to edit event categories

src/pages/userPage/personalData/AvatarAndProgressStatic.tsx
=> profileTimerDraw

src/pages/userPage/Menu/Menu.tsx
closes https://github.com/ita-social-projects/EPlast/issues/2709
=> Fix-#2709. 403 error on entering Blank and Event tabs of another user as Supporter user

src/components/Notifications/Messages.tsx, src/models/GllobalValidations/DescriptionValidation.tsx
closes https://github.com/ita-social-projects/EPlast/issues/2935
=> Fix-#2935. Name of hovel validation rules and error message fixed

src/pages/GoverningBody/GoverningBody/GoverningBodyAdministration.tsx, src/pages/GoverningBody/Sector/Sectors.tsx
closes https://github.com/ita-social-projects/EPlast/issues/2283
=> Fix #2283. URL and warning text modification

src/pages/Actions/ActionEvent/EventCategoriesEdit/EventCategoriesEdit.tsx, src/pages/Actions/ActionEvent/EventCategoriesEdit/EventCategoriesEditDrawer.tsx, src/pages/Actions/ActionEvent/EventCategoriesEdit/EventCategoriesEditFormValidators.ts, src/pages/Actions/ActionEvent/EventCategoriesEdit/EventCategoryEditForm.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCategoryCreateModal.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCreate.module.css, src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx, src/pages/Distinction/DistinctionTable/Form.module.css, src/pages/Distinction/DistinctionTable/FormEdit.module.css
Closes: https://github.com/ita-social-projects/EPlast/issues/2949
And I changed indent using spaces from 4 to 2 in some files
ToDo
ToDo
ToDo
=> Fix field was always empty and added scrolling

src/pages/Statistics/StatisticsCities.tsx
closes https://github.com/ita-social-projects/EPlast/issues/1439
=> Fix-#1439. Increased width of the city statistics table columns

src/pages/UserTable/ColumnsForUserTable.tsx, src/pages/UserTable/Interfaces/TableFilterParameters.tsx, src/pages/UserTable/UserTable.tsx
=> kadraFilterClient

src/pages/City/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx, src/pages/Club/AddAdministratorModal/AddAdministratorModal.tsx, src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx, src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx, src/pages/GoverningBody/AddAdministratorModal/EditAdministratorModal.tsx, src/pages/GoverningBody/Sector/AddSectorAdminForm.tsx, src/pages/GoverningBody/Sector/EditAdminModal.tsx, src/pages/Regions/AddAdministratorModal.tsx, src/pages/Regions/AddRegionSecretaryForm.tsx, src/pages/RegionsBoard/AddMainAdministratorModal/AddRegionBoardMainAdminForm.tsx, src/pages/RegionsBoard/EditAdministratorModal.tsx, src/pages/UserTable/AddRegionAdministratorForm.tsx, src/pages/UserTable/ChangeUserGoverningBodyForm.tsx
=> Make Date fields required to add/edit admin

src/pages/DecisionTable/Table.module.css, src/pages/DecisionTable/columns.tsx
Closes: https://github.com/ita-social-projects/EPlast/issues/2387
ToDo
ToDo
ToDo
=> Fix id field in decision table displayed incorrectly

src/pages/Actions/ActionEvent/EventUser/EventUser.tsx, src/pages/userPage/ActiveMembership/ActiveMembership.tsx, src/pages/userPage/Approvers/Approvers.tsx, src/pages/userPage/Blanks/Blanks.tsx, src/pages/userPage/Interface/Interface.tsx, src/pages/userPage/Secretaries/SecretariesPage.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx, src/pages/userPage/personalData/UserFields.tsx
=> timerDisplayFix

src/stores/StorePrecaution.tsx
closes https://github.com/ita-social-projects/EPlast/issues/2880
=> Fix-#2880. Date format fix

src/pages/UserRenewal/UserRenewal.tsx, src/pages/UserTable/UserTable.tsx
closes https://github.com/ita-social-projects/EPlast/issues/2957
=> Fix-#2957. Fixed link to user table tab from notifications

src/pages/UserTable/UserTable.tsx
=> Fixed user table tabs switching

src/stores/StorePrecaution.tsx
closes https://github.com/ita-social-projects/EPlast/issues/2880
=> Fix-2880. End date instead of invalid date fix

src/components/Header/Header.module.css
Fixed mobile layout for profile page
dev
ToDo
ToDo
ToDo
=> fixed bug #1495

src/pages/Club/Club/Club.tsx
=> Fix-2541. Displayed calendar fix

src/pages/Actions/ActionEvent/EventCategoriesEdit/EventCategoriesEdit.tsx, src/pages/Actions/ActionEvent/EventCategoriesEdit/EventCategoriesEditDrawer.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCreate.module.css, src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx, src/pages/Actions/ActionEvent/EventCreate/EventCreateDrawer.tsx, src/pages/Actions/ActionEvent/EventUser/EventUser.tsx, src/pages/Actions/EventTypes/EventTypes.tsx, src/pages/userPage/ActiveMembership/UserDates/UserFormerMembershipTable.tsx, src/pages/userPage/personalData/AvatarAndProgressStatic.tsx
Closes: https://github.com/ita-social-projects/EPlast/issues/2936
Coupled with: https://github.com/ita-social-projects/EPlast/pull/2960
ToDo
ToDo
ToDo
=> Added restrictions for editing event categories

src/pages/Precaution/PrecautionTable/columns.tsx
coupled with https://github.com/ita-social-projects/EPlast/pull/2973
=> Renamed precautions inside filter
